#!/usr/bin/env python3
"""
gen_fuzz.py -- randomized differential test-program generator for the APARA
compiler. Emits a self-contained C program (deterministic per seed) that mixes
the full supported feature set in one translation unit, because the bug class
that survives per-feature suites lives in WHOLE-PROGRAM SHAPE: which globals
exist, which functions coexist, how many temps each defines (cross-function
name-collision bugs), and which loop-opt tier the program lands on.

Every program follows the results[] golden convention, so compiler.py
independently verifies each slot against native gcc. The generator is
UB-free by construction so any mismatch is a compiler/toolchain bug:
  - all loops have constant bounds; recursion depth is a small constant;
  - shift amounts are masked; divisors are guaranteed nonzero;
  - multiplication operands are masked to 16 bits (no signed overflow);
  - no NaN can be constructed (float divisors bounded away from 0);
  - no unsigned-64 right shift (known simulator limit);
  - variadic args and >4-arg calls use long long only.

Usage: gen_fuzz.py SEED > prog.c
"""
import random
import sys


class Gen:
    def __init__(self, seed):
        self.r = random.Random(seed)
        self.seed = seed
        self.lines = []
        self.tmp_n = 0
        # feature mix for this program: each program enables a random subset,
        # so different seeds land on different loop-opt tiers / shapes
        r = self.r
        self.use_float   = r.random() < 0.45
        self.use_struct  = r.random() < 0.45
        self.use_fnptr   = r.random() < 0.40
        self.use_vararg  = r.random() < 0.35
        self.use_manyarg = r.random() < 0.40
        self.use_switch  = r.random() < 0.40
        self.use_ptr     = r.random() < 0.50
        self.use_recur   = r.random() < 0.35
        self.n_results   = r.randint(4, 6)

    # ── small helpers ─────────────────────────────────────────────────────────
    def w(self, s=''):
        self.lines.append(s)

    def tmp(self):
        self.tmp_n += 1
        return f"t{self.tmp_n}"

    # ── integer expressions (UB-free) ─────────────────────────────────────────
    def iexpr(self, vars_, depth=0):
        r = self.r
        if depth >= 2 or (vars_ and r.random() < 0.40):
            if vars_ and r.random() < 0.7:
                return r.choice(vars_)
            return str(r.randint(-50, 99))
        a = self.iexpr(vars_, depth + 1)
        b = self.iexpr(vars_, depth + 1)
        op = r.choice(['+', '-', '*', '&', '|', '^', '<<', '>>', '/', '%',
                       '<', '>', '==', '!=', '<=', '>='])
        if op == '*':
            return f"(((long long)({a}) & 0xffff) * (({b}) & 0xffff))"
        if op in ('<<', '>>'):
            # non-negative value, masked shift amount (also avoids u64>>)
            return f"(((long long)({a}) & 0xffffff) {op} ({r.randint(0, 15)}))"
        if op in ('/', '%'):
            return f"(({a}) {op} ((({b}) & 15) + 3))"
        return f"(({a}) {op} ({b}))"

    def fexpr(self, fvars, ivars, depth=0):
        r = self.r
        if depth >= 2 or (fvars and r.random() < 0.45):
            if fvars and r.random() < 0.7:
                return r.choice(fvars)
            if ivars and r.random() < 0.25:
                return f"(double)({r.choice(ivars)})"
            return f"{r.uniform(-8.0, 8.0):.4f}"
        a = self.fexpr(fvars, ivars, depth + 1)
        b = self.fexpr(fvars, ivars, depth + 1)
        op = r.choice(['+', '-', '*', '/'])
        if op == '/':
            # divisor bounded away from zero -> no inf/NaN
            return f"(({a}) / (({b}) * ({b}) + 1.5))"
        return f"(({a}) {op} ({b}))"

    # ── program parts ─────────────────────────────────────────────────────────
    def emit_header(self):
        self.w(f"/* fuzz seed {self.seed} -- generated by gen_fuzz.py */")
        if self.use_vararg:
            self.w("#ifdef __APARA__")
            self.w("long long *__va_start();")
            self.w("#define va_list long long *")
            self.w("#define va_start(ap, last) ((ap) = __va_start())")
            self.w("#define va_arg(ap, type)   ((type)*(ap)++)")
            self.w("#define va_end(ap)")
            self.w("#else")
            self.w("#include <stdarg.h>")
            self.w("#endif")
        self.w()

    def emit_globals(self):
        r = self.r
        self.w(f"long long results[{self.n_results}];")
        self.n_gd = r.randint(4, 8)
        vals = [r.randint(-40, 90) for _ in range(self.n_gd)]
        self.w(f"long long gd[{self.n_gd}] = {{{', '.join(map(str, vals))}}};")
        self.gscalars = []
        for i in range(r.randint(1, 3)):
            n = f"gs{i}"
            self.w(f"long long {n} = {r.randint(-30, 60)};")
            self.gscalars.append(n)
        if self.use_float:
            fv = [f"{r.uniform(-5, 5):.3f}" for _ in range(4)]
            self.w(f"double gf[4] = {{{', '.join(fv)}}};")
        if self.use_struct:
            self.w("struct P { long long x; long long y; long long w; };")
            inits = ', '.join(
                f"{{{r.randint(-9, 20)}, {r.randint(-9, 20)}, {r.randint(1, 9)}}}"
                for _ in range(3))
            self.w(f"struct P pts[3] = {{{inits}}};")
        self.w()

    def emit_int_fn(self, name, nparams):
        """A scalar helper: params -> long long, with loops/branches inside."""
        r = self.r
        ps = [f"p{i}" for i in range(nparams)]
        sig = ', '.join(f"long long {p}" for p in ps)
        self.w(f"long long {name}({sig}) {{")
        vars_ = list(ps) + self.gscalars
        acc = self.tmp()
        self.w(f"    long long {acc} = {self.iexpr(vars_)};")
        vars_.append(acc)
        n_stmts = r.randint(1, 3)
        for _ in range(n_stmts):
            kind = r.random()
            if kind < 0.35:           # bounded for loop over gd[]
                i = self.tmp()
                lim = r.randint(2, self.n_gd)
                self.w(f"    for (int {i} = 0; {i} < {lim}; {i}++)")
                self.w(f"        {acc} += gd[{i}] "
                       f"{r.choice(['+', '-', '^', '&'])} ({self.iexpr(vars_, 2)});")
            elif kind < 0.55:         # if/else
                self.w(f"    if (({self.iexpr(vars_, 2)}) > ({self.iexpr(vars_, 2)}))")
                self.w(f"        {acc} -= {self.iexpr(vars_, 2)};")
                self.w(f"    else")
                self.w(f"        {acc} ^= {self.iexpr(vars_, 2)};")
            elif kind < 0.70 and self.use_switch:
                v = self.tmp()
                self.w(f"    long long {v} = ({self.iexpr(vars_, 2)}) & 3;")
                self.w(f"    switch ({v}) {{")
                self.w(f"        case 0: {acc} += {r.randint(1, 30)}; break;")
                self.w(f"        case 1: {acc} -= {r.randint(1, 30)}; break;")
                self.w(f"        case 2: {acc} ^= {r.randint(1, 63)}; break;")
                self.w(f"        default: {acc} += {v}; break;")
                self.w(f"    }}")
            elif kind < 0.85 and self.use_ptr:
                p = self.tmp()
                self.w(f"    long long *{p} = gd + {r.randint(0, self.n_gd - 2)};")
                self.w(f"    {acc} += *{p} + {p}[1];")
            else:                      # while with a guaranteed-terminating count
                c = self.tmp()
                self.w(f"    long long {c} = {r.randint(2, 6)};")
                self.w(f"    while ({c} > 0) {{ {acc} += {c} * {r.randint(1, 9)}; {c}--; }}")
        self.w(f"    return {acc};")
        self.w("}")
        self.w()

    def emit_recur_fn(self):
        r = self.r
        self.w("long long rec(long long n, long long a) {")
        self.w("    if (n <= 0) return a;")
        self.w(f"    return rec(n - 1, a + n * {r.randint(1, 9)} + (a & 7));")
        self.w("}")
        self.w()

    def emit_float_fn(self):
        r = self.r
        self.w("double fmix(double a, double b) {")
        self.w(f"    double s = {self.fexpr(['a', 'b'], [])};")
        self.w(f"    if (a > b) s = s + {r.uniform(0.5, 2.5):.3f};")
        self.w(f"    else       s = s - b * {r.uniform(0.5, 1.5):.3f};")
        self.w("    return s;")
        self.w("}")
        self.w()

    def emit_vararg_fn(self):
        self.w("long long vsum(int n, ...) {")
        self.w("    va_list ap; long long s = 0;")
        self.w("    va_start(ap, n);")
        self.w("    for (int i = 0; i < n; i++) s += va_arg(ap, long long);")
        self.w("    va_end(ap);")
        self.w("    return s;")
        self.w("}")
        self.w()

    def emit_struct_fn(self):
        self.w("long long pdot(struct P *p, int n) {")
        self.w("    long long s = 0;")
        self.w("    for (int i = 0; i < n; i++) s += p[i].x * p[i].w - p[i].y;")
        self.w("    return s;")
        self.w("}")
        self.w()

    def emit_main(self, int_fns):
        r = self.r
        self.w("int main() {")
        vars_ = list(self.gscalars)
        # a few locals, maybe touched by pointer
        for i in range(r.randint(1, 2)):
            n = f"lv{i}"
            self.w(f"    long long {n} = {self.iexpr(vars_, 2)};")
            vars_.append(n)
        self.has_fp = False
        fp_ok = [f for f in int_fns if self.fn_params[f] <= 4]
        if self.use_fnptr and len(fp_ok) >= 2:
            self.has_fp = True
            f1, f2 = r.sample(fp_ok, 2)
            np1 = self.fn_params[f1]
            self.fp_np = np1
            self.w(f"    long long (*fp)({', '.join(['long long'] * np1)}) = {f1};")
            if self.fn_params[f2] == np1:
                self.w(f"    if (({self.iexpr(vars_, 2)}) > 0) fp = {f2};")
        ri = 0

        def call_int_fn(name):
            np = self.fn_params[name]
            args = ', '.join(self.iexpr(vars_, 2) for _ in range(np))
            return f"{name}({args})"

        while ri < self.n_results:
            kind = r.random()
            if kind < 0.30 and int_fns:
                self.w(f"    results[{ri}] = {call_int_fn(r.choice(int_fns))};")
            elif kind < 0.40 and self.has_fp:
                args = ', '.join(self.iexpr(vars_, 2) for _ in range(self.fp_np))
                self.w(f"    results[{ri}] = fp({args});")
            elif kind < 0.50 and self.use_vararg:
                n = r.randint(0, 6)
                args = ''.join(f", (long long)({self.iexpr(vars_, 2)})" for _ in range(n))
                self.w(f"    results[{ri}] = vsum({n}{args});")
            elif kind < 0.60 and self.use_recur:
                self.w(f"    results[{ri}] = rec({r.randint(3, 8)}, {self.iexpr(vars_, 2)});")
            elif kind < 0.70 and self.use_struct:
                self.w(f"    results[{ri}] = pdot(pts, 3) + pts[{r.randint(0, 2)}].y;")
            elif kind < 0.80 and self.use_float:
                fa = self.fexpr(['gf[0]', 'gf[1]', 'gf[2]', 'gf[3]'], vars_, 2)
                self.w(f"    results[{ri}] = (long long)(fmix({fa}, gf[{r.randint(0, 3)}]) * 16.0);")
            elif kind < 0.90:
                # loop accumulating calls -- the shape that exposed the LICM bug
                acc = self.tmp()
                i = self.tmp()
                self.w(f"    long long {acc} = 0;")
                if int_fns:
                    fn = r.choice(int_fns)
                    np = self.fn_params[fn]
                    args = ', '.join(
                        r.choice([i, f"{i} * {r.randint(2, 5)}", self.iexpr(vars_, 2)])
                        for _ in range(np))
                    self.w(f"    for (long long {i} = 0; {i} < {r.randint(2, 4)}; {i}++)")
                    self.w(f"        {acc} += {fn}({args});")
                else:
                    self.w(f"    for (long long {i} = 0; {i} < {r.randint(2, 5)}; {i}++)")
                    self.w(f"        {acc} += gd[{i} % {self.n_gd}] * {i};")
                self.w(f"    results[{ri}] = {acc};")
            else:
                self.w(f"    results[{ri}] = {self.iexpr(vars_)};")
            ri += 1
        self.w("    return 1;")
        self.w("}")

    def generate(self):
        r = self.r
        self.emit_header()
        self.emit_globals()
        self.fn_params = {}
        int_fns = []
        n_int_fns = r.randint(1, 2)
        for i in range(n_int_fns):
            name = f"fn{i}"
            # mix small and >4 param counts
            np = r.choice([1, 2, 3, 2, 5, 6] if self.use_manyarg else [1, 2, 3])
            self.fn_params[name] = np
            self.emit_int_fn(name, np)
            int_fns.append(name)
        if self.use_recur:
            self.emit_recur_fn()
        if self.use_float:
            self.emit_float_fn()
        if self.use_vararg:
            self.emit_vararg_fn()
        if self.use_struct:
            self.emit_struct_fn()
        self.emit_main(int_fns)
        return '\n'.join(self.lines) + '\n'


if __name__ == '__main__':
    seed = int(sys.argv[1])
    sys.stdout.write(Gen(seed).generate())
