#!/usr/bin/env python3
"""
gen_full.py -- full-surface randomized program generator for the 1000-program
APARA verification campaign (testing/fuzz1000/).

Extends testing/fuzz/gen_fuzz.py's shape mixing with the REST of the supported
C surface so that, together with the directed battery (directed/*.c), the
campaign touches every instruction, sub-instruction and datatype the compiler
can emit (audited by cov_scan.py -- coverage is MEASURED on the emitted mcode,
not assumed):
  - all integer widths signed+unsigned (char/short/int/long long) as globals,
    arrays and locals (sub-word $ld sign/zero-extension paths);
  - 2D arrays, unions, bit-fields, enums, static locals, goto, do-while,
    ternary/comma, compound assignment;
  - f32 AND f64 arithmetic/comparison/casts;
  - intrinsics (vector ALU, dot, vreduce, cmov, slice, pack, nand/abs/...);
  - plus everything from the v1 generator: function pointers, variadics,
    >4-arg functions, recursion, struct pointers.

Same UB-freedom rules as v1 (bounded loops/recursion, masked shifts, guarded
divisors, 64-bit-forced shift/multiply width, no NaN, no u64>>), so every
mismatch vs the gcc golden run is a real toolchain bug.

Usage: gen_full.py SEED > prog.c
"""
import random
import sys

INT_TYPES = [  # (ctype, mask_for_safe_store, is_unsigned)
    ('char', 0x7f, False), ('unsigned char', 0xff, True),
    ('short', 0x7fff, False), ('unsigned short', 0xffff, True),
    ('int', 0x7fffffff, False), ('unsigned int', 0xffffffff, True),
    ('long long', None, False),
]


class Gen:
    def __init__(self, seed):
        self.r = random.Random(seed)
        self.seed = seed
        self.lines = []
        self.tmp_n = 0
        r = self.r
        self.use_float   = r.random() < 0.50
        self.use_f32     = r.random() < 0.40
        self.use_struct  = r.random() < 0.40
        self.use_fnptr   = r.random() < 0.35
        self.use_vararg  = r.random() < 0.30
        self.use_manyarg = r.random() < 0.35
        self.use_switch  = r.random() < 0.35
        self.use_ptr     = r.random() < 0.45
        self.use_recur   = r.random() < 0.30
        self.use_subword = r.random() < 0.55
        self.use_2d      = r.random() < 0.40
        self.use_union   = r.random() < 0.25
        self.use_bitf    = r.random() < 0.25
        self.use_enum    = r.random() < 0.30
        self.use_static  = r.random() < 0.30
        self.use_goto    = r.random() < 0.25
        self.use_intrin  = r.random() < 0.45
        self.n_results   = r.randint(4, 6)

    def w(self, s=''):
        self.lines.append(s)

    def tmp(self):
        self.tmp_n += 1
        return f"t{self.tmp_n}"

    # ── expressions (UB-free, 64-bit-forced where width matters) ──────────────
    def iexpr(self, vars_, depth=0):
        r = self.r
        if depth >= 2 or (vars_ and r.random() < 0.40):
            if vars_ and r.random() < 0.7:
                return r.choice(vars_)
            return str(r.randint(-50, 99))
        a = self.iexpr(vars_, depth + 1)
        b = self.iexpr(vars_, depth + 1)
        op = r.choice(['+', '-', '*', '&', '|', '^', '<<', '>>', '/', '%',
                       '<', '>', '==', '!=', '<=', '>=', '?:', ','])
        if op == '*':
            return f"(((long long)({a}) & 0xffff) * (({b}) & 0xffff))"
        if op in ('<<', '>>'):
            return f"(((long long)({a}) & 0xffffff) {op} ({r.randint(0, 15)}))"
        if op in ('/', '%'):
            return f"(({a}) {op} ((({b}) & 15) + 3))"
        if op == '?:':
            return f"((({a}) > ({b})) ? ({a}) : ({b}))"
        if op == ',':
            return f"(({a}), ({b}))"
        return f"(({a}) {op} ({b}))"

    def fexpr(self, fvars, ivars, depth=0):
        r = self.r
        if depth >= 2 or (fvars and r.random() < 0.45):
            if fvars and r.random() < 0.7:
                return r.choice(fvars)
            if ivars and r.random() < 0.25:
                return f"(double)({r.choice(ivars)})"
            return f"{r.uniform(-8.0, 8.0):.4f}"
        a = self.fexpr(fvars, ivars, depth + 1)
        b = self.fexpr(fvars, ivars, depth + 1)
        op = r.choice(['+', '-', '*', '/'])
        if op == '/':
            return f"(({a}) / (({b}) * ({b}) + 1.5))"
        return f"(({a}) {op} ({b}))"

    # ── globals ───────────────────────────────────────────────────────────────
    def emit_header(self):
        self.w(f"/* fuzz1000 seed {self.seed} -- generated by gen_full.py */")
        if self.use_vararg:
            self.w("#ifdef __APARA__")
            self.w("long long *__va_start();")
            self.w("#define va_list long long *")
            self.w("#define va_start(ap, last) ((ap) = __va_start())")
            self.w("#define va_arg(ap, type)   ((type)*(ap)++)")
            self.w("#define va_end(ap)")
            self.w("#else")
            self.w("#include <stdarg.h>")
            self.w("#endif")
        if self.use_intrin:
            self.w("long long __nand(long long, long long);")
            self.w("long long __abs(long long);")
            self.w("long long __max(long long, long long);")
            self.w("long long __min(long long, long long);")
            self.w("long long __vadd_vi16(long long, long long);")
            self.w("long long __vreduce_vi16(long long);")
            self.w("int __cmov_gt(int, int, int);")
        self.w()

    def emit_globals(self):
        r = self.r
        self.w(f"long long results[{self.n_results}];")
        self.n_gd = r.randint(4, 6)
        vals = [r.randint(-40, 90) for _ in range(self.n_gd)]
        self.w(f"long long gd[{self.n_gd}] = {{{', '.join(map(str, vals))}}};")
        self.gscalars = []
        for i in range(r.randint(1, 2)):
            n = f"gs{i}"
            self.w(f"long long {n} = {r.randint(-30, 60)};")
            self.gscalars.append(n)
        if self.use_subword:
            self.sub_t, mask, _ = r.choice(INT_TYPES[:6])
            lim = mask if mask and mask < 100 else 100
            vals = [r.randint(0, min(lim, 99)) for _ in range(4)]
            self.w(f"{self.sub_t} sw[4] = {{{', '.join(map(str, vals))}}};")
        if self.use_2d:
            rows = [f"{{{r.randint(-9, 30)}, {r.randint(-9, 30)}, {r.randint(-9, 30)}}}"
                    for _ in range(3)]
            self.w(f"long long m2[3][3] = {{{', '.join(rows)}}};")
        if self.use_float:
            fv = [f"{r.uniform(-5, 5):.3f}" for _ in range(4)]
            self.w(f"double gf[4] = {{{', '.join(fv)}}};")
        if self.use_f32:
            fv = [f"{r.uniform(-4, 4):.2f}f" for _ in range(4)]
            self.w(f"float g32[4] = {{{', '.join(fv)}}};")
        if self.use_struct:
            self.w("struct P { long long x; long long y; long long w; };")
            inits = ', '.join(
                f"{{{r.randint(-9, 20)}, {r.randint(-9, 20)}, {r.randint(1, 9)}}}"
                for _ in range(3))
            self.w(f"struct P pts[3] = {{{inits}}};")
        if self.use_union:
            self.w("union U { long long ll; int iv; };")
        if self.use_bitf:
            self.w("struct BF { unsigned a : 5; unsigned b : 7; unsigned c : 9; };")
        if self.use_enum:
            self.w(f"enum E {{ EA = {r.randint(1, 9)}, EB = {r.randint(10, 30)}, EC }};")
        self.w()

    # ── helper functions ──────────────────────────────────────────────────────
    def emit_int_fn(self, name, nparams):
        r = self.r
        ps = [f"p{i}" for i in range(nparams)]
        sig = ', '.join(f"long long {p}" for p in ps)
        self.w(f"long long {name}({sig}) {{")
        vars_ = list(ps) + self.gscalars
        acc = self.tmp()
        self.w(f"    long long {acc} = {self.iexpr(vars_)};")
        vars_.append(acc)
        for _ in range(r.randint(1, 2)):
            kind = r.random()
            if kind < 0.20:
                i = self.tmp()
                self.w(f"    for (int {i} = 0; {i} < {r.randint(2, self.n_gd)}; {i}++)")
                self.w(f"        {acc} {r.choice(['+=', '-=', '^='])} gd[{i}] "
                       f"{r.choice(['+', '-', '&'])} ({self.iexpr(vars_, 2)});")
            elif kind < 0.35:
                self.w(f"    if (({self.iexpr(vars_, 2)}) > ({self.iexpr(vars_, 2)}))")
                self.w(f"        {acc} -= {self.iexpr(vars_, 2)};")
                self.w(f"    else")
                self.w(f"        {acc} ^= {self.iexpr(vars_, 2)};")
            elif kind < 0.45 and self.use_switch:
                v = self.tmp()
                self.w(f"    long long {v} = ({self.iexpr(vars_, 2)}) & 3;")
                self.w(f"    switch ({v}) {{")
                self.w(f"        case 0: {acc} += {r.randint(1, 30)};")  # fall through
                self.w(f"        case 1: {acc} -= {r.randint(1, 30)}; break;")
                self.w(f"        case 2: {acc} ^= {r.randint(1, 63)}; break;")
                self.w(f"        default: {acc} += {v}; break;")
                self.w(f"    }}")
            elif kind < 0.55 and self.use_subword:
                i = self.tmp()
                self.w(f"    for (int {i} = 0; {i} < 4; {i}++) {acc} += sw[{i}];")
            elif kind < 0.65 and self.use_2d:
                i, j = self.tmp(), self.tmp()
                self.w(f"    for (int {i} = 0; {i} < 3; {i}++)")
                self.w(f"        for (int {j} = 0; {j} < 3; {j}++)")
                self.w(f"            {acc} += m2[{i}][{j}] * ({i} + 1);")
            elif kind < 0.72 and self.use_goto:
                g1 = self.tmp()
                self.w(f"    if (({acc} & 1) == 0) goto skip_{g1};")
                self.w(f"    {acc} += {r.randint(1, 20)};")
                self.w(f"skip_{g1}:")
                self.w(f"    {acc} += 1;")
            elif kind < 0.80 and self.use_ptr:
                p = self.tmp()
                self.w(f"    long long *{p} = gd + {r.randint(0, self.n_gd - 2)};")
                self.w(f"    {acc} += *{p} + {p}[1];")
            elif kind < 0.88 and self.use_intrin:
                self.w(f"    {acc} += __max(__abs({self.iexpr(vars_, 2)}), "
                       f"__min({acc}, {r.randint(1, 40)}));")
            else:
                c = self.tmp()
                self.w(f"    long long {c} = {r.randint(2, 5)};")
                self.w(f"    do {{ {acc} += {c}; {c}--; }} while ({c} > 0);")
        self.w(f"    return {acc};")
        self.w("}")
        self.w()

    def emit_special_fns(self):
        r = self.r
        if self.use_recur:
            self.w("long long rec(long long n, long long a) {")
            self.w(f"    if (n <= 0) return a;")
            self.w(f"    return rec(n - 1, a + n * {r.randint(1, 9)} + (a & 7));")
            self.w("}")
            self.w()
        if self.use_float:
            self.w("double fmix(double a, double b) {")
            self.w(f"    double s = {self.fexpr(['a', 'b'], [])};")
            self.w(f"    if (a > b) s = s + {r.uniform(0.5, 2.5):.3f};")
            self.w(f"    else       s = s - b * {r.uniform(0.5, 1.5):.3f};")
            self.w("    return s;")
            self.w("}")
            self.w()
        if self.use_f32:
            self.w("float f32mix(float a, float b) {")
            self.w(f"    float s = a * {r.uniform(0.5, 2.0):.2f}f + b;")
            self.w(f"    if (s > a) s = s - b * 0.5f;")
            self.w("    return s;")
            self.w("}")
            self.w()
        if self.use_vararg:
            self.w("long long vsum(int n, ...) {")
            self.w("    va_list ap; long long s = 0;")
            self.w("    va_start(ap, n);")
            self.w("    for (int i = 0; i < n; i++) s += va_arg(ap, long long);")
            self.w("    va_end(ap);")
            self.w("    return s;")
            self.w("}")
            self.w()
        if self.use_struct:
            self.w("long long pdot(struct P *p, int n) {")
            self.w("    long long s = 0;")
            self.w("    for (int i = 0; i < n; i++) s += p[i].x * p[i].w - p[i].y;")
            self.w("    return s;")
            self.w("}")
            self.w()
        if self.use_static:
            self.w("long long counter(long long step) {")
            self.w("    static long long c = 0;")
            self.w("    c += step;")
            self.w("    return c;")
            self.w("}")
            self.w()

    # ── main ──────────────────────────────────────────────────────────────────
    def emit_main(self, int_fns):
        r = self.r
        self.w("int main() {")
        vars_ = list(self.gscalars)
        for i in range(r.randint(1, 2)):
            n = f"lv{i}"
            self.w(f"    long long {n} = {self.iexpr(vars_, 2)};")
            vars_.append(n)
        self.has_fp = False
        fp_ok = [f for f in int_fns if self.fn_params[f] <= 4]
        if self.use_fnptr and len(fp_ok) >= 2:
            self.has_fp = True
            f1, f2 = r.sample(fp_ok, 2)
            self.fp_np = self.fn_params[f1]
            self.w(f"    long long (*fp)({', '.join(['long long'] * self.fp_np)}) = {f1};")
            if self.fn_params[f2] == self.fp_np:
                self.w(f"    if (({self.iexpr(vars_, 2)}) > 0) fp = {f2};")
        ri = 0
        while ri < self.n_results:
            kind = r.random()
            if kind < 0.22 and int_fns:
                fn = r.choice(int_fns)
                args = ', '.join(self.iexpr(vars_, 2)
                                 for _ in range(self.fn_params[fn]))
                self.w(f"    results[{ri}] = {fn}({args});")
            elif kind < 0.30 and self.has_fp:
                args = ', '.join(self.iexpr(vars_, 2) for _ in range(self.fp_np))
                self.w(f"    results[{ri}] = fp({args});")
            elif kind < 0.38 and self.use_vararg:
                n = r.randint(0, 5)
                args = ''.join(f", (long long)({self.iexpr(vars_, 2)})"
                               for _ in range(n))
                self.w(f"    results[{ri}] = vsum({n}{args});")
            elif kind < 0.44 and self.use_recur:
                self.w(f"    results[{ri}] = rec({r.randint(3, 7)}, "
                       f"{self.iexpr(vars_, 2)});")
            elif kind < 0.50 and self.use_struct:
                self.w(f"    results[{ri}] = pdot(pts, 3) + pts[{r.randint(0, 2)}].y;")
            elif kind < 0.56 and self.use_float:
                fa = self.fexpr(['gf[0]', 'gf[1]', 'gf[2]', 'gf[3]'], vars_, 2)
                self.w(f"    results[{ri}] = (long long)(fmix({fa}, "
                       f"gf[{r.randint(0, 3)}]) * 16.0);")
            elif kind < 0.61 and self.use_f32:
                self.w(f"    results[{ri}] = (long long)(f32mix(g32[{r.randint(0, 3)}], "
                       f"g32[{r.randint(0, 3)}]) * 8.0f);")
            elif kind < 0.66 and self.use_static:
                self.w(f"    results[{ri}] = counter({r.randint(1, 9)}) + "
                       f"counter({r.randint(1, 9)});")
            elif kind < 0.71 and self.use_union:
                # same-member round-trip only: cross-member punning depends on
                # the DMEM sub-word layout (APARA high-half vs x86 low-half)
                # and would be a false differential failure, not a bug
                u = self.tmp()
                self.w(f"    union U {u}; {u}.iv = ({self.iexpr(vars_, 2)}) & 0x7fff;")
                self.w(f"    results[{ri}] = {u}.iv * 3 + 1;")
            elif kind < 0.76 and self.use_bitf:
                b = self.tmp()
                self.w(f"    struct BF {b}; {b}.a = {r.randint(0, 31)}; "
                       f"{b}.b = {r.randint(0, 127)}; {b}.c = {r.randint(0, 511)};")
                self.w(f"    results[{ri}] = {b}.a + {b}.b * 2 + {b}.c;")
            elif kind < 0.80 and self.use_enum:
                self.w(f"    results[{ri}] = EA + EB * 2 + EC;")
            elif kind < 0.85 and self.use_intrin:
                a, b = self.iexpr(vars_, 2), self.iexpr(vars_, 2)
                self.w(f"    results[{ri}] = __nand({a}, {b}) & 0xffff;")
            elif kind < 0.92:
                acc, i = self.tmp(), self.tmp()
                self.w(f"    long long {acc} = 0;")
                if int_fns:
                    fn = r.choice(int_fns)
                    args = ', '.join(
                        r.choice([i, f"{i} * {r.randint(2, 5)}",
                                  self.iexpr(vars_, 2)])
                        for _ in range(self.fn_params[fn]))
                    self.w(f"    for (long long {i} = 0; {i} < {r.randint(2, 3)}; {i}++)")
                    self.w(f"        {acc} += {fn}({args});")
                else:
                    self.w(f"    for (long long {i} = 0; {i} < {r.randint(2, 5)}; {i}++)")
                    self.w(f"        {acc} += gd[{i} % {self.n_gd}] * {i};")
                self.w(f"    results[{ri}] = {acc};")
            else:
                self.w(f"    results[{ri}] = {self.iexpr(vars_)};")
            ri += 1
        self.w("    return 1;")
        self.w("}")

    def generate(self):
        r = self.r
        self.emit_header()
        self.emit_globals()
        self.fn_params = {}
        int_fns = []
        for i in range(r.randint(1, 2)):
            name = f"fn{i}"
            np = r.choice([1, 2, 3, 2, 5, 6] if self.use_manyarg else [1, 2, 3])
            self.fn_params[name] = np
            self.emit_int_fn(name, np)
            int_fns.append(name)
        self.emit_special_fns()
        self.emit_main(int_fns)
        return '\n'.join(self.lines) + '\n'


if __name__ == '__main__':
    sys.stdout.write(Gen(int(sys.argv[1])).generate())
