"""
APARA VLIW Bundle Optimizer

Post-processes generated mcode (1 instruction per bundle) and repacks
independent instructions into multi-instruction bundles (max 8),
respecting VLIW data hazards:

  RAW (Read After Write) : B reads a reg that A writes  → SPLIT
  WAW (Write After Write): both write the same reg       → SPLIT
  WAR (Write After Read) : B writes a reg that A read   → SAFE
        (VLIW reads all operands simultaneously before any writes)

Control-flow rules:
  - branch / $call / $return / $halt must be the LAST instruction in a bundle
  - a label forces a new bundle boundary (label attaches to bundle start)

Bundle sizes must be power-of-2 (mcode_align handles null padding):
  1, 2, 4, 8 instructions per bundle
"""

import re

# ── Register dependency parser ─────────────────────────────────────────────────

def _parse_deps(text):
    """
    Parse one APARA instruction text.
    Returns (writes: frozenset, reads: frozenset, is_ctrl: bool)

    Handles all instruction forms generated by codegen.py:
      ALU    : op $rd ($iN) $rs1 rs2_or_imm
      Load   : $ld ($iN) $rd [$rb + off_or_reg]
      Store  : $st ($iN) [$rb + off_or_reg] $rs
      Set    : $set $rd N val
      Branch : ? ($iN) $r op $goto label
      Call   : $call label
      Return : $return
      Halt   : $halt
      Null   : $null
    """
    t = text.strip()

    if not t or t == '$null':
        return frozenset(), frozenset(), False

    if t in ('$halt', '$return'):
        return frozenset(), frozenset(), True

    if t.startswith('$call'):
        # $call clobbers r1 (return value written on return)
        return frozenset({'$r1'}), frozenset(), True

    if t.startswith('$set'):
        # $set $rd N val  →  writes rd
        m = re.match(r'\$set\s+(\$r\d+)', t)
        return (frozenset({m.group(1)}) if m else frozenset()), frozenset(), False

    if t.startswith('$ld'):
        # $ld ($iN) $rd [$rb + off]   off = integer or $reg
        m = re.match(r'\$ld\s+\(\$i\d+\)\s+(\$r\d+)\s+\[(\$r\d+)\s*\+\s*(-?\d+|\$r\d+)\]', t)
        if m:
            rd, rb, off = m.group(1), m.group(2), m.group(3)
            reads = {rb}
            if off.startswith('$r'):
                reads.add(off)
            return frozenset({rd}), frozenset(reads), False
        return frozenset(), frozenset(), False

    if t.startswith('$st'):
        # $st ($iN) [$rb + off] $rs   off = integer or $reg
        m = re.match(r'\$st\s+\(\$i\d+\)\s+\[(\$r\d+)\s*\+\s*(-?\d+|\$r\d+)\]\s+(\$r\d+)', t)
        if m:
            rb, off, rs = m.group(1), m.group(2), m.group(3)
            reads = {rb, rs}
            if off.startswith('$r'):
                reads.add(off)
            return frozenset(), frozenset(reads), False
        return frozenset(), frozenset(), False

    if t.startswith('?'):
        # ? ($iN) $r op $goto label  →  reads r; ends bundle
        m = re.match(r'\?\s+\(\$i\d+\)\s+(\$r\d+)', t)
        reads = frozenset({m.group(1)}) if m else frozenset()
        return frozenset(), reads, True

    # ALU: op $rd ($iN) $rs1 rs2_or_imm
    # op may be: + - * / << >> | & ^ ~| ~& ~^
    m = re.match(r'([+\-*/<>&|^~]{1,3})\s+(\$r\d+)\s+\(\$i\d+\)\s+(\$r\d+)\s+(-?\d+|\$r\d+)', t)
    if m:
        rd, rs1, rs2 = m.group(2), m.group(3), m.group(4)
        reads = {rs1}
        if rs2.startswith('$r'):
            reads.add(rs2)
        reads.discard('$r0')   # $r0 is always-zero hardware constant — never a real dep
        return frozenset({rd}), frozenset(reads), False

    return frozenset(), frozenset(), False


# ── Mcode text parser ──────────────────────────────────────────────────────────

def _parse_flat(mcode_text):
    """
    Parse mcode text into a flat list of instruction dicts:
      { 'text': str, 'labels': [str], 'writes': frozenset,
        'reads': frozenset, 'is_ctrl': bool }

    Also returns the header lines (comments/blanks before first bundle).
    """
    lines = mcode_text.split('\n')
    flat          = []
    pending_lbl   = []
    header        = []
    seen_content  = False
    i = 0

    while i < len(lines):
        line = lines[i]
        s    = line.strip()
        i   += 1

        # Collect header (comments / blanks before first label or bundle)
        if not seen_content:
            if not s or s.startswith('//'):
                header.append(line)
                continue

        if not s or s.startswith('//'):
            continue

        # Label line
        if s.endswith(':') and s != '||':
            seen_content = True
            pending_lbl.append(s[:-1])
            continue

        # Bundle open
        if s == '||':
            seen_content = True
            bundle_texts = []
            while i < len(lines) and lines[i].strip() != ';':
                t = lines[i].strip()
                if t and t != '$null':
                    bundle_texts.append(t)
                i += 1
            i += 1  # skip ';'

            if bundle_texts:
                for j, itext in enumerate(bundle_texts):
                    w, r, ctrl = _parse_deps(itext)
                    flat.append({
                        'text':    itext,
                        'labels':  pending_lbl if j == 0 else [],
                        'writes':  w,
                        'reads':   r,
                        'is_ctrl': ctrl,
                    })
                    pending_lbl = []
            else:
                # Empty bundle carrying only labels (e.g. trailing label)
                if pending_lbl:
                    flat.append({
                        'text': '$null', 'labels': pending_lbl,
                        'writes': frozenset(), 'reads': frozenset(), 'is_ctrl': False,
                    })
                    pending_lbl = []

    return header, flat


# ── Greedy bundle packer ───────────────────────────────────────────────────────

def _pack_bundles(flat):
    """
    Greedy forward pass: pack instructions into bundles of up to 8.
    Returns list of {'labels': [...], 'instrs': [str]}.
    """
    bundles  = []
    c_labels = []
    c_instrs = []
    c_writes = set()
    c_ctrl   = False

    def flush():
        if c_instrs or c_labels:
            bundles.append({'labels': list(c_labels), 'instrs': list(c_instrs)})

    def reset():
        c_labels.clear(); c_instrs.clear(); c_writes.clear()
        nonlocal c_ctrl; c_ctrl = False

    for instr in flat:
        split = False
        if c_instrs:
            if instr['labels']:                         split = True  # label → new bundle
            elif c_ctrl:                                split = True  # ctrl ends bundle
            elif instr['reads']  & c_writes:           split = True  # RAW hazard
            elif instr['writes'] & c_writes:           split = True  # WAW hazard
            elif len(c_instrs) >= 8:                   split = True  # bundle full

        if split:
            flush(); reset()

        c_labels.extend(instr['labels'])
        c_instrs.append(instr['text'])
        c_writes |= instr['writes']
        c_ctrl    = c_ctrl or instr['is_ctrl']

    flush()
    return bundles


# ── Emitter ───────────────────────────────────────────────────────────────────

def _emit_bundles(header, bundles):
    out = list(header)
    for b in bundles:
        for lbl in b['labels']:
            out.append(f"{lbl}:")
        out.append("||")
        for itext in b['instrs']:
            out.append(f"    {itext}")
        out.append(";")
    return '\n'.join(out) + '\n'


# ── Public API ────────────────────────────────────────────────────────────────

def bundle_mcode(mcode_text):
    """
    Repack mcode from 1-instruction bundles into VLIW bundles (max 8).

    Returns:
        (new_mcode_text: str, n_before: int, n_after: int)
    """
    header, flat  = _parse_flat(mcode_text)
    n_before      = sum(1 for x in flat if x['text'] != '$null')
    bundles       = _pack_bundles(flat)
    n_after       = len(bundles)
    new_mcode     = _emit_bundles(header, bundles)
    return new_mcode, n_before, n_after
