"""
APARA VLIW Bundle Optimizer

Post-processes generated mcode (1 instruction per bundle) and repacks
independent instructions into multi-instruction bundles (max 8),
respecting VLIW data hazards:

  RAW (Read After Write) : B reads a reg that A writes  → SPLIT
  WAW (Write After Write): both write the same reg       → SPLIT
  WAR (Write After Read) : B writes a reg that A read   → SAFE
        (VLIW reads all operands simultaneously before any writes)

Memory hazards (same rationale, applied to DMEM addresses instead of registers):

  store → load/store of the SAME [base + offset]  → SPLIT
        (a bundle's instructions execute in parallel; a load packed into the
         same bundle as a preceding store does NOT see that store's value —
         it reads the stale pre-store data. Confirmed on hardware 2026-06-17.)
  load → store of the same address                 → SAFE
        (same WAR reasoning as registers: all reads happen before any writes)

  Address equality is matched textually on (base_reg, offset) — exact same
  base register and exact same offset (literal or register name). This is
  sound only because any register whose value changed since entering the
  current (not-yet-split) bundle window would already have forced a split
  via the existing RAW/WAW register-hazard checks above.

Control-flow rules:
  - branch / $call / $return / $halt must be the LAST instruction in a bundle
  - a label forces a new bundle boundary (label attaches to bundle start)

Bundle sizes must be power-of-2 (mcode_align handles null padding):
  1, 2, 4, 8 instructions per bundle
"""

import os
import re
import sys
from collections import defaultdict

# ── Register dependency parser ─────────────────────────────────────────────────

def _mem_may_alias(acc, writes):
    """May memory access `acc` (base, off) alias ANY store address in `writes`?
    Two accesses are provably DISJOINT only when they share the same base
    register and have different constant offsets. Different base registers
    prove nothing -- two registers can hold the same address (e.g. two temps
    both computed as FP-16), so they must be treated as a conflict. Tuple
    equality alone missed exactly that: a store via $r8 and a load via $r9 of
    the same stack slot landed in one bundle and the load read stale data
    (fp03 j=-3 garbage, 2026-07-18)."""
    ab, ao = acc
    for wb, wo in writes:
        # provably disjoint: same base register, different constant offsets
        disjoint = (ab == wb and ao != wo
                    and not ao.startswith('$') and not wo.startswith('$'))
        if not disjoint:
            return True
    return False


# ── R6.2: symbolic memory dependence interface ────────────────────────────────
#
# `_mem_may_alias` above is a purely TEXTUAL rule: it proves independence only
# for one base register with different constant offsets. R6.1 measured what that
# costs -- an unrolled vector loop's stores serialise the next copy's loads even
# when the objects are provably distinct -- so R6.2 adds a symbolic address model
# (vector_backend/memory_objects.py) and consults it FIRST.
#
# The scheduling algorithm is unchanged. Only the answer to "can these two
# accesses touch the same memory?" got sharper, and only in the safe direction:
# `_proved_independent` returns True only for a proof, so every unproven pair
# falls through to exactly the behaviour this file had before. Set
# APARA_NO_MEMDISAMB=1 to restore the textual rule alone.

def _proved_independent(a, b):
    """True only when the symbolic model PROVES the two accesses disjoint."""
    if a is None or b is None:
        return False
    if a.get('mem_ref') is None or b.get('mem_ref') is None:
        return False
    try:
        from vector_backend.mem_dependence import independent
        return independent(a, b)
    except Exception:
        return False            # analysis must never break a build


def _annotate_memrefs(flat):
    """Attach symbolic memory references to a parsed instruction list. A failure
    leaves the list untouched, which simply restores the pre-R6.2 behaviour."""
    if os.environ.get('APARA_NO_MEMDISAMB'):
        return flat
    try:
        from vector_backend.mem_dependence import annotate
        return annotate(flat)
    except Exception:
        return flat


def _is_div_sqrt(t):
    """Occupies the single divide/sqrt lane: scalar '/', $fsqrt, vector '/'."""
    return t.startswith(('/', '$fsqrt')) or bool(re.match(r'\$v\s*/', t))


def _parse_deps(text):
    """
    Parse one APARA instruction text.
    Returns (writes: frozenset, reads: frozenset, is_ctrl: bool,
             mem_access: (base, offset) or None, mem_write: (base, offset) or None)

    mem_access is set for $ld AND $st (any memory access at that address).
    mem_write  is set for $st only (a store landing at that address).

    Handles all instruction forms generated by codegen.py:
      ALU    : op $rd ($iN) $rs1 rs2_or_imm
      Load   : $ld ($iN) $rd [$rb + off_or_reg]
      Store  : $st ($iN) [$rb + off_or_reg] $rs
      Set    : $set $rd N val
      Branch : ? ($iN) $r op $goto label
      Call   : $call label
      Return : $return
      Halt   : $halt
      Null   : $null
    """
    t = text.strip()
    NONE3 = (frozenset(), frozenset(), False, None, None)

    if not t or t == '$null':
        return NONE3

    if t in ('$halt', '$return'):
        return frozenset(), frozenset(), True, None, None

    if t.startswith('$call'):
        # $call clobbers r1 (return value written on return).
        # Register-indirect form ($call $rN) also READS the target register --
        # without this the bundler could pack the instruction that computes the
        # target into the same bundle as the call itself (stale read).
        m = re.match(r'\$call\s+(\$r\d+)', t)
        reads = frozenset({m.group(1)}) if m else frozenset()
        return frozenset({'$r1'}), reads, True, None, None

    if t.startswith('$set'):
        # $set $rd N val  →  writes rd
        m = re.match(r'\$set\s+(\$r\d+)', t)
        return (frozenset({m.group(1)}) if m else frozenset()), frozenset(), False, None, None

    if t.startswith('$ld'):
        # $ld ($[iuf]N) $rd [$rb + off]   off = integer or $reg
        # N>64 (u128/u256) writes a register PAIR/QUAD starting at rd, not just rd --
        # a single $ld fills multiple consecutive registers in that case.
        # The tag may be $f32/$f64 (float load) -- it MUST be parsed for hazards
        # too, or the load's dest/base registers and memory access go untracked.
        m = re.match(r'\$ld\s+\(\$[iuf](\d+)\)\s+(\$r\d+)\s+\[(\$r\d+)\s*\+\s*(-?\d+|\$r\d+)\]', t)
        if m:
            nbits, rd, rb, off = m.group(1), m.group(2), m.group(3), m.group(4)
            n_regs = max(1, int(nbits) // 64)
            rd_num = int(rd[2:])
            writes = {f'$r{rd_num + i}' for i in range(n_regs)}
            reads = {rb}
            if off.startswith('$r'):
                reads.add(off)
            return frozenset(writes), frozenset(reads), False, (rb, off), None
        return frozenset(), frozenset(), False, None, None

    if t.startswith('$st'):
        # $st ($[iuf]N) [$rb + off] $rs   off = integer or $reg
        # N>64 (u128/u256) READS a register PAIR/QUAD starting at rs, not just rs --
        # a single $st reads multiple consecutive registers as its source group
        # (same convention as $ld's dest group; see isa.g mcode_store_instruction).
        # Float tags ($f32/$f64) must be parsed for hazards too (as for $ld).
        m = re.match(r'\$st\s+\(\$[iuf](\d+)\)\s+\[(\$r\d+)\s*\+\s*(-?\d+|\$r\d+)\]\s+(\$r\d+)', t)
        if m:
            nbits, rb, off, rs = m.group(1), m.group(2), m.group(3), m.group(4)
            n_regs = max(1, int(nbits) // 64)
            rs_num = int(rs[2:])
            reads = {rb} | {f'$r{rs_num + i}' for i in range(n_regs)}
            if off.startswith('$r'):
                reads.add(off)
            return frozenset(), frozenset(reads), False, (rb, off), (rb, off)
        return frozenset(), frozenset(), False, None, None

    if t.startswith('$pack'):
        # $pack packed_nbits rd word_nbits rs2
        # rs2 and rs2+1 form a consecutive register pair — BOTH are read, even though
        # only rs2 appears in the text. Missing this caused a RAW hazard to go undetected
        # when an adjacent instruction wrote rs2+1 in the same bundle (found 2026-06-17).
        m = re.match(r'\$pack\s+\d+\s+(\$r\d+)\s+\d+\s+(\$r\d+)', t)
        if m:
            rd, rs2 = m.group(1), m.group(2)
            partner = f'$r{int(rs2[2:]) + 1}'
            return frozenset({rd}), frozenset({rs2, partner}), False, None, None
        return NONE3

    if t.startswith('$cast'):
        # $cast (dest_type) rd (src_type) rs
        m = re.match(r'\$cast\s+\(\$\w+\)\s+(\$r\d+)\s+\(\$\w+\)\s+(\$r\d+)', t)
        if m:
            rd, rs = m.group(1), m.group(2)
            return frozenset({rd}), frozenset({rs}), False, None, None
        return NONE3

    if t.startswith('$fsqrt'):
        # $fsqrt rd (type) rs
        m = re.match(r'\$fsqrt\s+(\$r\d+)\s+\(\$\w+\)\s+(\$r\d+)', t)
        if m:
            rd, rs = m.group(1), m.group(2)
            return frozenset({rd}), frozenset({rs}), False, None, None
        return NONE3

    if t.startswith('$cmov'):
        # $cmov ? (type) check cond rd src_true
        # rd is BOTH read (kept unchanged if the condition is false) and written.
        m = re.match(r'\$cmov\s+\?\s+\(\$\w+\)\s+(\$r\d+)\s+\S+\s+(\$r\d+)\s+(\$r\d+)', t)
        if m:
            check, rd, src_true = m.group(1), m.group(2), m.group(3)
            return frozenset({rd}), frozenset({check, rd, src_true}), False, None, None
        return NONE3

    if t.startswith('$slice'):
        # $slice rd hindex lindex rs
        m = re.match(r'\$slice\s+(\$r\d+)\s+\d+\s+\d+\s+(\$r\d+)', t)
        if m:
            rd, rs = m.group(1), m.group(2)
            return frozenset({rd}), frozenset({rs}), False, None, None
        return NONE3

    if t.startswith('$v ') or t.startswith('$v\t'):
        # $v op rd (type) rs1 rs2 [$replicate]
        m = re.match(r'\$v\s+\S+\s+(\$r\d+)\s+\(\$\w+\)\s+(\$r\d+)\s+(\$r\d+)', t)
        if m:
            rd, rs1, rs2 = m.group(1), m.group(2), m.group(3)
            return frozenset({rd}), frozenset({rs1, rs2}), False, None, None
        return NONE3

    if t.startswith('$dot'):
        # $dot [$accumulate] rd (type) rs1 rs2
        # accumulate form also READS rd (rd := (rs1 dot rs2) + rd).
        m = re.match(r'\$dot\s+(\$accumulate\s+)?(\$r\d+)\s+\(\$\w+\)\s+(\$r\d+)\s+(\$r\d+)', t)
        if m:
            accumulate, rd, rs1, rs2 = m.group(1), m.group(2), m.group(3), m.group(4)
            reads = {rs1, rs2}
            if accumulate:
                reads.add(rd)
            return frozenset({rd}), frozenset(reads), False, None, None
        return NONE3

    if t.startswith('$vreduce'):
        # $vreduce + rd (type) rs  (sub-opcode '+' required by the grammar)
        m = re.match(r'\$vreduce\s+\S+\s+(\$r\d+)\s+\(\$\w+\)\s+(\$r\d+)', t)
        if m:
            rd, rs = m.group(1), m.group(2)
            return frozenset({rd}), frozenset({rs}), False, None, None
        return NONE3

    if t.startswith('?'):
        # ? ($iN) $r op $goto label  →  reads r; ends bundle
        m = re.match(r'\?\s+\(\$[iuf]\d+\)\s+(\$r\d+)', t)
        reads = frozenset({m.group(1)}) if m else frozenset()
        return frozenset(), reads, True, None, None

    # ALU: op $rd ($iN)/($uN)/($fN) $rs1 rs2_or_imm
    # op may be: + - * / << >> | & ^ ~| ~& ~^
    # The type tag may be integer ($iN), unsigned ($uN) or float ($fN) — a float
    # arithmetic op has the same operand layout, so it MUST be parsed for hazards
    # too (else the bundler treats it as dependency-free and reorders it before
    # its operands are built).
    m = re.match(r'([+\-*/<>&|^~]{1,3})\s+(\$r\d+)\s+\(\$[iuf]\d+\)\s+(\$r\d+)\s+(-?\d+|\$r\d+)', t)
    if m:
        rd, rs1, rs2 = m.group(2), m.group(3), m.group(4)
        reads = {rs1}
        if rs2.startswith('$r'):
            reads.add(rs2)
        reads.discard('$r0')   # $r0 is always-zero hardware constant — never a real dep
        return frozenset({rd}), frozenset(reads), False, None, None

    return NONE3


# ── Mcode text parser ──────────────────────────────────────────────────────────

def _parse_flat(mcode_text):
    """
    Parse mcode text into a flat list of instruction dicts:
      { 'text': str, 'labels': [str], 'writes': frozenset,
        'reads': frozenset, 'is_ctrl': bool }

    Also returns the header lines (comments/blanks before first bundle).
    """
    lines = mcode_text.split('\n')
    flat          = []
    pending_lbl   = []
    header        = []
    seen_content  = False
    i = 0

    while i < len(lines):
        line = lines[i]
        s    = line.strip()
        i   += 1

        # Collect header (comments / blanks before first label or bundle)
        if not seen_content:
            if not s or s.startswith('//'):
                header.append(line)
                continue

        if not s or s.startswith('//'):
            continue

        # Label line
        if s.endswith(':') and s != '||':
            seen_content = True
            pending_lbl.append(s[:-1])
            continue

        # Bundle open
        if s == '||':
            seen_content = True
            bundle_texts = []
            while i < len(lines) and lines[i].strip() != ';':
                t = lines[i].strip()
                # Keep $null: codegen only emits it for an explicit __nop()
                # (never as padding), so dropping it here silently deleted the
                # user's nop (fuzz1000 coverage audit, 2026-07-19).
                if t:
                    bundle_texts.append(t)
                i += 1
            i += 1  # skip ';'

            if bundle_texts:
                for j, itext in enumerate(bundle_texts):
                    w, r, ctrl, mem_access, mem_write = _parse_deps(itext)
                    flat.append({
                        'text':       itext,
                        'labels':     pending_lbl if j == 0 else [],
                        'writes':     w,
                        'reads':      r,
                        'is_ctrl':    ctrl,
                        'mem_access': mem_access,
                        'mem_write':  mem_write,
                    })
                    pending_lbl = []
            else:
                # Empty bundle carrying only labels (e.g. trailing label)
                if pending_lbl:
                    flat.append({
                        'text': '$null', 'labels': pending_lbl,
                        'writes': frozenset(), 'reads': frozenset(), 'is_ctrl': False,
                        'mem_access': None, 'mem_write': None,
                    })
                    pending_lbl = []

    return header, flat


# ── Greedy bundle packer ───────────────────────────────────────────────────────

# Display order / full taxonomy for the split-reason instrumentation below.
# WAR is listed for completeness but is NEVER a packer split reason: WAR is safe
# inside a VLIW bundle (all operands are read before any write), so _pack_bundles
# has no WAR branch and its count is always 0. WAR only constrains the *scheduler*
# (_must_precede), not the packer.
_SPLIT_REASONS = ['RAW', 'WAW', 'WAR', 'MemAlias', 'MemPhase', 'MemLane',
                  'FUnit', 'Control', 'Call', 'Label', 'BundleFull', 'Other']


def _report_bundle_stats(stats, gstats, blk_instrs, show_all=False):
    """Print per-basic-block and global split-reason histograms to stderr.

    Instrumentation only: called solely when APARA_BUNDLE_STATS is set, and it
    reads already-collected counters -- it has no effect on the packed bundles.
    """
    def _hist(counter, title, extra=''):
        total = sum(counter.values())
        if total == 0:
            return
        print(f"\n{title}{extra}", file=sys.stderr)
        for r in sorted(counter, key=lambda k: (-counter[k],
                        _SPLIT_REASONS.index(k) if k in _SPLIT_REASONS else 99)):
            print(f"  {r:<11}{counter[r]:>7}  {100.0 * counter[r] / total:5.1f}%",
                  file=sys.stderr)

    # Most-split blocks first: that is where bundle occupancy is being lost.
    blocks = sorted(stats.items(), key=lambda kv: -sum(kv[1].values()))
    if not show_all:
        blocks = blocks[:15]
    print("\n==== BUNDLE SPLIT REASONS (per basic block) ====", file=sys.stderr)
    for key, counter in blocks:
        splits = sum(counter.values())
        instrs = blk_instrs.get(key, 0)
        _hist(counter, f"Block {key}", f"   ({instrs} instrs, {splits} splits)")

    print("\n==== BUNDLE SPLIT REASONS (global) ====", file=sys.stderr)
    _hist(gstats, "GLOBAL", f"   ({sum(gstats.values())} total splits)")
    print("\nlegend: RAW/WAW=register deps  MemAlias/MemPhase=memory deps  "
          "MemLane/FUnit=hardware lanes  Control/Call/Label=structural boundaries",
          file=sys.stderr)


def _pack_bundles(flat):
    """
    Greedy forward pass: pack instructions into bundles of up to 8.
    Returns list of {'labels': [...], 'instrs': [str]}.
    """
    bundles    = []
    c_labels   = []
    c_instrs   = []
    c_writes   = set()
    c_mem_writes = []      # store INSTRUCTIONS already in this bundle (R6.2:
                           # the whole instruction, so its symbolic memory
                           # reference is available, not just its (base,offset))
    c_mem_reads  = set()   # registers read by $ld/$st instructions in this bundle
    c_ctrl     = False
    c_ls       = 0         # load/store count (hardware lane limit: 4 per bundle)
    c_divsqrt  = 0         # divide/sqrt count (hardware lane limit: 1 per bundle)

    def flush():
        if c_instrs or c_labels:
            bundles.append({'labels': list(c_labels), 'instrs': list(c_instrs)})

    def reset():
        c_labels.clear(); c_instrs.clear(); c_writes.clear(); c_mem_writes.clear()
        c_mem_reads.clear()
        nonlocal c_ctrl, c_ls, c_divsqrt
        c_ctrl = False; c_ls = 0; c_divsqrt = 0

    # ABI-fixed stack-pointer register (matches codegen.py's SP = '$r27'). bundler.py
    # works purely on parsed text and doesn't otherwise know ABI register roles, so
    # this is hardcoded rather than imported.
    SP_REG = '$r27'

    # ── Split-reason instrumentation (side-effect-free) ──────────────────────
    # For every instruction rejected from the current bundle, record the ONE
    # primary reason. The split decision is an if/elif cascade, so exactly one
    # branch fires per rejection -> the categories are mutually exclusive by
    # construction and cannot double-count. Counters are keyed by basic block
    # (a labelled instruction, or a fall-through after a control transfer,
    # starts a new block). None of this affects `bundles`; it only prints when
    # APARA_BUNDLE_STATS is set.
    stats      = defaultdict(lambda: defaultdict(int))   # block_key -> reason -> count
    gstats     = defaultdict(int)                        # global   reason -> count
    blk_instrs = defaultdict(int)                        # block_key -> instrs seen
    blk_id     = 0
    blk_key    = '0000:entry'
    prev_ctrl  = False

    for instr in flat:
        # Basic-block tracking for the per-block histogram.
        if instr['labels']:
            blk_id += 1
            blk_key = f"{blk_id:04d}:{instr['labels'][0]}"
        elif prev_ctrl:
            blk_id += 1
            blk_key = f"{blk_id:04d}:<fallthrough>"
        prev_ctrl = instr['is_ctrl']
        blk_instrs[blk_key] += 1

        is_mem  = instr['mem_access'] is not None
        is_call = instr['text'].startswith('$call')
        is_ls   = instr['text'].startswith(('$ld', '$st'))
        is_ds   = _is_div_sqrt(instr['text'])
        split  = False
        reason = 'Other'
        if c_instrs:
            if instr['labels']:                         split = True; reason = 'Label'    # label → new bundle
            elif c_ctrl:                                split = True; reason = 'Control'  # ctrl ends bundle
            elif instr['reads']  & c_writes:           split = True; reason = 'RAW'      # RAW hazard
            elif instr['writes'] & c_writes:           split = True; reason = 'WAW'      # WAW hazard
            elif (instr['mem_access'] is not None
                  and _conflicts_with_stores(instr, c_mem_writes)):
                                                        split = True; reason = 'MemAlias'  # memory RAW/WAW hazard
            # Phase hazard: the aligner places $ld/$st in LATER slots than ALU/$set
            # instructions within a bundle, regardless of textual order — confirmed
            # 2026-06-17 by comparing unaligned vs aligned mcode (e.g. every function
            # prologue's "$st [SP+0] OLD_FP" + "+FP=SP" bundle: the store textually
            # comes first to capture the OLD FP, but the aligner moves it to a later
            # slot than the FP update, so it ends up storing the NEW FP instead).
            # So a non-memory instruction writing a register that an already-bundled
            # memory instruction reads is unsafe — the memory read will see the new
            # (post-ALU) value, not the pre-bundle one the compiler intended.
            elif not is_mem and (instr['writes'] & c_mem_reads): split = True; reason = 'MemPhase'
            # Conservative fix (2026-06-17): never bundle $call with an instruction
            # that modifies SP. The exact phase interaction between an SP-modifying
            # ALU instruction and a co-bundled $call is unconfirmed (breaks even the
            # simplest possible function call — see memory/project_call_phase_hazard.md)
            # — rather than guess at the precise mechanism, force them into separate
            # bundles. This pattern only occurs near call sites, so the cost is a few
            # extra instruction slots, not a systemic bundling regression.
            elif is_call and SP_REG in c_writes:        split = True; reason = 'Call'
            # Hardware lane limits (McodeProgram::alignFullBundleToLanes):
            # a full bundle has 4 load/store lanes and 1 divide/sqrt lane.
            # Exceeding them makes mcode_align FAIL its lane placement — it
            # prints an Error but still emits the bundle with the CTI not in
            # lane 0, and the sim's return-address math then jumps into the
            # middle of a bundle (fuzz seed 68, 2026-07-18: five independent
            # caller-save stores packed with a $call).
            elif is_ls and c_ls >= 4:                  split = True; reason = 'MemLane'    # ld/st lanes full
            elif is_ds and c_divsqrt >= 1:             split = True; reason = 'FUnit'      # div/sqrt lane full
            elif len(c_instrs) >= 8:                   split = True; reason = 'BundleFull'  # bundle full

        if split:
            stats[blk_key][reason] += 1
            gstats[reason] += 1
            flush(); reset()

        c_labels.extend(instr['labels'])
        c_instrs.append(instr['text'])
        c_writes |= instr['writes']
        if instr['mem_write'] is not None:
            c_mem_writes.append(instr)
        if is_mem:
            c_mem_reads |= instr['reads']
        c_ctrl    = c_ctrl or instr['is_ctrl']
        if is_ls:
            c_ls += 1
        if is_ds:
            c_divsqrt += 1

    flush()

    _stats_env = os.environ.get('APARA_BUNDLE_STATS')
    if _stats_env:
        _report_bundle_stats(stats, gstats, blk_instrs, show_all=(_stats_env == 'all'))
    return bundles


def _conflicts_with_stores(acc, store_instrs):
    """May `acc` touch memory any already-bundled store writes?

    Per store: the R6.2 symbolic proof first, then the original textual rule.
    Identical to the pre-R6.2 answer whenever nothing is proved."""
    for st in store_instrs:
        if _proved_independent(acc, st):
            continue
        if _mem_may_alias(acc['mem_access'], (st['mem_write'],)):
            return True
    return False


def _merge_duplicate_labels(bundles):
    """
    The assembler grammar only allows one label directly before a bundle's '||'
    (confirmed: "expecting PARALLEL, found <label>" if a second one follows).
    When a bundle ends up with multiple labels — e.g. an inner for-loop's exit
    label lands on the exact same bundle as an outer loop's increment label,
    with no real instruction between them — collapse them to one canonical
    label and rewrite every $goto/$call reference to the dropped labels so
    they point at the canonical one instead. ($call $rN, register-indirect,
    is never matched here since the regex requires a bare identifier with no
    leading $.)
    """
    rename = {}
    for b in bundles:
        if len(b['labels']) > 1:
            canonical = b['labels'][0]
            for extra in b['labels'][1:]:
                rename[extra] = canonical
            b['labels'] = [canonical]
    if not rename:
        return bundles
    pattern = re.compile(r'(\$goto|\$call)(\s+)(\w+)')
    def _sub(m):
        kw, sp, lbl = m.group(1), m.group(2), m.group(3)
        return f"{kw}{sp}{rename.get(lbl, lbl)}"
    for b in bundles:
        b['instrs'] = [pattern.sub(_sub, itext) for itext in b['instrs']]
    return bundles


# ── Emitter ───────────────────────────────────────────────────────────────────

# ── R9.5: alignment-aware bundle formation ────────────────────────────────────
#
# mcode_align gives every bundle a CAPACITY (see `_bundle_capacity`, and the
# block comment above `resolve_code_labels`): 8 if it holds a CTI / load / store
# / divide, otherwise the instruction count rounded up to 1, 2, 4 or 8. A bundle
# is then placed at the next address that is a MULTIPLE OF ITS CAPACITY, and the
# gap is filled with `pad_*` bundles of `$null`. Each pad bundle issues, so it
# costs a TICK -- measured post-R9.3: 35.0% of all bundles are pads and roughly
# 31.7% of runtime is spent on them (`R9_4_POST_R9_3_FINAL_ANALYSIS.md`).
#
# Which bundles cause that? Only the ones whose capacity is LESS than 8, i.e.
# pure-ALU bundles of 1-4 instructions. A capacity-8 bundle starting at a
# multiple of 8 leaves the address a multiple of 8, so a RUN OF CAPACITY-8
# BUNDLES IS SELF-ALIGNING and needs no padding at all. A small ALU bundle in
# the middle of such a run knocks the address off the boundary, and every
# following full bundle then pays up to three pad bundles (the pad count for a
# gap g is popcount(g): g=7 -> pads of 1,2,4).
#
# So the decision this pass makes is deliberately narrow: inside a LOOP, pad a
# sub-capacity bundle out to 8 slots with `$null` so it stops breaking the
# alignment run. Nothing is reordered, no hazard rule is consulted or changed,
# no instruction is added or removed -- `$null` is architecturally a no-op, and
# the bundle's real instructions and their order are untouched. Straight-line
# code outside loops is left alone, because its pads execute once and the IMEM
# would be spent for nothing.
#
# Measured on gemm vi16 (candidates evaluated through the real toolchain):
#     production            7037 ticks   26 pads   392 IMEM words
#     loops only (this)     4375 ticks   12 pads   408 IMEM words  -37.8% / +4.1%
#     every bundle          4366 ticks    0 pads   432 IMEM words  -38.0% / +10.2%
# Widening everything buys 0.2 points more for 2.5x the IMEM, so this pass
# widens loop bundles only.
#
# Kill switch: APARA_NO_ALIGN_BUNDLE=1 restores the R9.3 layout exactly.

_ALIGN_WIDEN_DISABLED = os.environ.get('APARA_NO_ALIGN_BUNDLE', '') not in ('', '0')

ISSUE_WIDTH = 8


def _loop_depth(bundles):
    """Loop nesting depth per bundle, from BACKWARD branches in the emitted
    stream. A bundle is 'in a loop' if some later bundle branches to a label at
    or before it. Purely structural -- no profile is needed and none exists at
    this stage."""
    at = {}
    for idx, b in enumerate(bundles):
        for l in b['labels']:
            at.setdefault(l, idx)
    depth = [0] * len(bundles)
    for idx, b in enumerate(bundles):
        for t in b['instrs']:
            m = re.search(r'\$goto\s+(\S+)', t)
            if m and m.group(1) in at and at[m.group(1)] <= idx:
                for k in range(at[m.group(1)], idx + 1):
                    depth[k] += 1
    return depth


def _align_aware_widen(bundles):
    """Pad loop-resident sub-capacity bundles out to the full issue width.

    Returns (bundles, n_widened). The instruction lists are only ever EXTENDED
    with `$null`; nothing is moved, removed or reordered."""
    if _ALIGN_WIDEN_DISABLED:
        return bundles, 0
    depth = _loop_depth(bundles)
    n = 0
    for b, d in zip(bundles, depth):
        if d < 1:
            continue                       # straight-line code: pads run once
        if not b['instrs']:
            continue
        if _bundle_capacity(b['instrs']) >= ISSUE_WIDTH:
            continue                       # already a full bundle: self-aligning
        b['instrs'] = list(b['instrs']) + \
            ['$null'] * (ISSUE_WIDTH - len(b['instrs']))
        n += 1
    return bundles, n


def _emit_bundles(header, bundles):
    out = list(header)
    for b in bundles:
        for lbl in b['labels']:
            out.append(f"{lbl}:")
        out.append("||")
        for itext in b['instrs']:
            out.append(f"    {itext}")
        out.append(";")
    return '\n'.join(out) + '\n'


# ── Instruction scheduling (list scheduling within basic blocks) ───────────────

_SP_REG = '$r27'

def _mem_pair_conflict(a, b):
    """True if memory accesses a and b may conflict and so must stay ordered.

    Order matters only when at least one access is a STORE and it may alias the
    other access's address. Aliasing uses the exact same disjointness proof the
    bundle packer trusts (_mem_may_alias): two accesses are provably disjoint
    only when they share the same base register and have different CONSTANT
    offsets. Everything else (different base registers, register offsets, same
    address) is treated as a possible conflict.

    Two loads never conflict (no store involved) -> free to reorder, as before.

    Soundness of dropping the order for a provably-disjoint pair: the proof
    relies on the shared base register holding the same value at both accesses.
    If some instruction between them redefines that base register, the RAW/WAR/
    WAW register checks in _must_precede already force an ordering edge through
    that writer, so the pair cannot be reordered regardless. And _pack_bundles
    re-applies _mem_may_alias against the bundle's stores as the final gate.
    """
    if a['mem_access'] is None or b['mem_access'] is None:
        return False
    if _proved_independent(a, b):
        return False            # R6.2: provably distinct memory, free to reorder
    if a['mem_write'] is not None and _mem_may_alias(b['mem_access'], (a['mem_write'],)):
        return True
    if b['mem_write'] is not None and _mem_may_alias(a['mem_access'], (b['mem_write'],)):
        return True
    return False


def _must_precede(a, b):
    """True if instruction a (earlier in program order) MUST stay before b for
    the reordering to be semantically identical. Covers all real dependencies:
      RAW  a writes / b reads
      WAW  a writes / b writes
      WAR  a reads  / b writes   (anti-dependence -- needed after reg reuse)
      memory ordering (only when the accesses MAY alias -- see _mem_pair_conflict;
        provably-disjoint accesses are free to reorder)
      call / control-transfer act as full barriers.
    Conservative by design: extra edges only cost optimization, never correctness.
    """
    if a['writes'] & b['reads']:   return True   # RAW
    if a['writes'] & b['writes']:  return True   # WAW
    if a['reads']  & b['writes']:  return True   # WAR
    if _mem_pair_conflict(a, b):                 return True   # memory conflict
    if a['is_ctrl'] or b['is_ctrl']:             return True
    if a['text'].startswith('$call') or b['text'].startswith('$call'):
        return True
    return False

def _schedule_block(block):
    """Reorder one basic block (list scheduling) so that mutually-independent
    instructions end up adjacent, letting the greedy packer form denser bundles.
    Only independent instructions are ever moved past one another, so the result
    is semantically identical to the input."""
    m = len(block)
    if m <= 2:
        return block
    block_labels = [l for ins in block for l in ins['labels']]
    items = [dict(ins, labels=[]) for ins in block]
    preds = [set() for _ in range(m)]
    for j in range(m):
        for i in range(j):
            if _must_precede(items[i], items[j]):
                preds[j].add(i)
    done = [False] * m
    sched = []
    # mirror of the open bundle, used only as a clustering heuristic (the real
    # packing + hazard checks are redone by _pack_bundles afterwards)
    cw, cmr = set(), set()
    cmw = []                       # store instructions in the mirrored bundle
    cctrl = [False]; csize = [0]; cls = [0]; cds = [0]
    def can_join(ins):
        if cctrl[0] or csize[0] >= 8:                     return False
        if ins['reads']  & cw:                            return False
        if ins['writes'] & cw:                            return False
        if ins['mem_access'] is not None and _conflicts_with_stores(ins, cmw): return False
        if ins['mem_access'] is None and (ins['writes'] & cmr):        return False
        if ins['text'].startswith('$call') and _SP_REG in cw:         return False
        # hardware lane limits (mirrors _pack_bundles): 4 ld/st, 1 div/sqrt
        if ins['text'].startswith(('$ld', '$st')) and cls[0] >= 4:    return False
        if _is_div_sqrt(ins['text']) and cds[0] >= 1:                 return False
        return True
    def open_with(ins):
        cw.update(ins['writes'])
        if ins['mem_write'] is not None: cmw.append(ins)
        if ins['mem_access'] is not None: cmr.update(ins['reads'])
        cctrl[0] = cctrl[0] or ins['is_ctrl']; csize[0] += 1
        if ins['text'].startswith(('$ld', '$st')): cls[0] += 1
        if _is_div_sqrt(ins['text']): cds[0] += 1
    def reset():
        cw.clear(); del cmw[:]; cmr.clear(); cctrl[0] = False; csize[0] = 0
        cls[0] = 0; cds[0] = 0
    def is_ready(k):
        return not done[k] and all(done[p] for p in preds[k])
    for _ in range(m):
        pick = next((k for k in range(m) if is_ready(k) and can_join(items[k])), -1)
        if pick < 0:
            reset()
            pick = next((k for k in range(m) if is_ready(k)), -1)
        if pick < 0:                                   # safety: never happens for a DAG
            pick = next(k for k in range(m) if not done[k]); reset()
        done[pick] = True; sched.append(items[pick]); open_with(items[pick])
    if block_labels:
        sched[0]['labels'] = block_labels
    return sched

def _schedule_within_blocks(flat):
    """Split the flat instruction list into basic blocks (a labelled instruction
    starts one; a control-transfer ends one) and list-schedule each block."""
    blocks, cur = [], []
    for ins in flat:
        if ins['labels'] and cur:
            blocks.append(cur); cur = []
        cur.append(ins)
        if ins['is_ctrl']:
            blocks.append(cur); cur = []
    if cur:
        blocks.append(cur)
    out = []
    for b in blocks:
        out.extend(_schedule_block(b))
    return out


# ── Public API ────────────────────────────────────────────────────────────────

def bundle_mcode(mcode_text, schedule=True, disambiguate=True):
    """
    Repack mcode from 1-instruction bundles into VLIW bundles (max 8).

    `disambiguate` attaches R6.2 symbolic memory references before scheduling,
    so the packer and the list scheduler can tell provably-distinct accesses
    apart. Pass False (or set APARA_NO_MEMDISAMB) for the pre-R6.2 textual rule.

    Returns:
        (new_mcode_text: str, n_before: int, n_after: int)
    """
    header, flat  = _parse_flat(mcode_text)
    n_before      = sum(1 for x in flat if x['text'] != '$null')
    if disambiguate:
        flat      = _annotate_memrefs(flat)
    if schedule:
        flat      = _schedule_within_blocks(flat)
    bundles       = _pack_bundles(flat)
    bundles       = _merge_duplicate_labels(bundles)
    # R9.5: decide emitted WIDTHS so mcode_align has less to pad. Runs last, on
    # the final bundle list, so the layout `resolve_code_labels` then computes is
    # the one that ships. Adds only `$null`; never reorders or repacks.
    bundles, _widened = _align_aware_widen(bundles)
    n_after       = len(bundles)
    new_mcode     = _emit_bundles(header, bundles)
    if os.environ.get('APARA_BUNDLE_STATS') and _widened:
        print(f"[align] widened {_widened} loop bundles to {ISSUE_WIDTH} slots")
    return new_mcode, n_before, n_after


# ── Code-label address resolution (post-bundling linker pass) ─────────────────
#
# The assembler's $set grammar only accepts numeric immediates, so a function's
# code address can never be materialized via "$set rd 0 <label>" at the
# assembler level. But the final instruction address of every label IS fully
# determined by bundle layout, which mcode_align computes with a simple rule
# (McodeProgram::Align_Bundles + McodeInstructionBundle::Calculate_Capacity):
#
#   capacity = 8 if the bundle holds any CTI (?-branch / $call / $return),
#              load/store, divide, or $fsqrt (it must be a "full bundle");
#              otherwise the instruction count rounded up to 1 / 2 / 4 / 8.
#   Each bundle is null-padded to its capacity and placed at the next address
#   aligned to that capacity (pad bundles fill the gap). For full bundles the
#   aligner then moves the CTI to lane 0, so a $call's own instruction address
#   equals its bundle's base address.
#
# Replicating that here lets the COMPILER act as the linker: it patches two
# kinds of $set placeholders after bundling (layout never changes afterwards --
# the substitution is text-only and 1:1):
#
#   $set $rN 0 <function_label>  ->  the label's absolute word address
#                                    (function-pointer VALUES are absolute)
#   $set $rN 0 __icall_<K>       ->  the bundle address of the NEXT
#                                    register-indirect "$call $rM" in program
#                                    order. The hardware's indirect call is
#                                    PC-RELATIVE (npc = call_addr + reg), so
#                                    codegen subtracts this from the absolute
#                                    target right before the call.

def _forces_full_bundle(t):
    """Mirror of the assembler's Has_Cti/Has_Load_Store/Has_Div_Sqrt check."""
    if t.startswith(('$ld', '$st', '$call', '$return', '$goto', '?', '$fsqrt')):
        return True
    if t.startswith('/'):                 # scalar divide (int or float)
        return True
    if re.match(r'\$v\s*/', t):           # vector divide
        return True
    return False


def _bundle_capacity(instrs):
    if any(_forces_full_bundle(t) for t in instrs):
        return 8
    n = len(instrs)
    for c in (1, 2, 4, 8):
        if n <= c:
            return c
    raise ValueError(f"bundle with {n} instructions exceeds the 8-slot limit")


def resolve_code_labels(mcode_text):
    """Patch $set code-label placeholders (see block comment above) using the
    exact bundle addresses mcode_align will assign. No-op for programs without
    placeholders. Raises RuntimeError on an unresolvable placeholder."""
    lines = mcode_text.split('\n')

    # Pass 1: group lines into bundles, keeping line indices of instructions.
    bundles, cur, pending = [], None, []
    for i, line in enumerate(lines):
        s = line.strip()
        if not s or s.startswith('//'):
            continue
        if s == '||':
            cur = {'labels': pending, 'instr_idx': []}
            pending = []
        elif s == ';':
            if cur is not None:
                bundles.append(cur)
            cur = None
        elif s.endswith(':') and cur is None:
            pending.append(s[:-1])
        elif cur is not None:
            cur['instr_idx'].append(i)

    # Pass 2: assign aligned addresses, exactly as mcode_align will.
    label_addr, addr = {}, 0
    for b in bundles:
        cap = _bundle_capacity([lines[i].strip() for i in b['instr_idx']])
        if addr % cap:
            addr += cap - (addr % cap)
        for lbl in b['labels']:
            label_addr[lbl] = addr
        b['addr'] = addr
        addr += cap

    # Pass 3: patch placeholders in place (text-only, layout unchanged).
    set_re = re.compile(r'^(\s*\$set\s+\$r\d+\s+0\s+)([A-Za-z_]\w*)\s*$')
    flat = [(b, li) for b in bundles for li in b['instr_idx']]
    for pos, (b, li) in enumerate(flat):
        m = set_re.match(lines[li])
        if not m:
            continue
        name = m.group(2)
        if name.startswith('__icall_'):
            target = None
            for b2, l2 in flat[pos + 1:]:
                if re.match(r'\$call\s+\$r\d+', lines[l2].strip()):
                    target = b2['addr']
                    break
            if target is None:
                raise RuntimeError(
                    f"indirect-call placeholder '{name}' has no following "
                    f"register-indirect $call")
            lines[li] = m.group(1) + str(target)
        elif name in label_addr:
            a = label_addr[name]
            if a > 0xFFFF:
                raise RuntimeError(
                    f"code label '{name}' address 0x{a:x} exceeds $set's "
                    f"16-bit immediate field")
            lines[li] = m.group(1) + str(a)
        else:
            raise RuntimeError(f"$set references unknown code label '{name}'")

    return '\n'.join(lines)
