"""
APARA VLIW Bundle Optimizer

Post-processes generated mcode (1 instruction per bundle) and repacks
independent instructions into multi-instruction bundles (max 8),
respecting VLIW data hazards:

  RAW (Read After Write) : B reads a reg that A writes  → SPLIT
  WAW (Write After Write): both write the same reg       → SPLIT
  WAR (Write After Read) : B writes a reg that A read   → SAFE
        (VLIW reads all operands simultaneously before any writes)

Memory hazards (same rationale, applied to DMEM addresses instead of registers):

  store → load/store of the SAME [base + offset]  → SPLIT
        (a bundle's instructions execute in parallel; a load packed into the
         same bundle as a preceding store does NOT see that store's value —
         it reads the stale pre-store data. Confirmed on hardware 2026-06-17.)
  load → store of the same address                 → SAFE
        (same WAR reasoning as registers: all reads happen before any writes)

  Address equality is matched textually on (base_reg, offset) — exact same
  base register and exact same offset (literal or register name). This is
  sound only because any register whose value changed since entering the
  current (not-yet-split) bundle window would already have forced a split
  via the existing RAW/WAW register-hazard checks above.

Control-flow rules:
  - branch / $call / $return / $halt must be the LAST instruction in a bundle
  - a label forces a new bundle boundary (label attaches to bundle start)

Bundle sizes must be power-of-2 (mcode_align handles null padding):
  1, 2, 4, 8 instructions per bundle
"""

import re

# ── Register dependency parser ─────────────────────────────────────────────────

def _parse_deps(text):
    """
    Parse one APARA instruction text.
    Returns (writes: frozenset, reads: frozenset, is_ctrl: bool,
             mem_access: (base, offset) or None, mem_write: (base, offset) or None)

    mem_access is set for $ld AND $st (any memory access at that address).
    mem_write  is set for $st only (a store landing at that address).

    Handles all instruction forms generated by codegen.py:
      ALU    : op $rd ($iN) $rs1 rs2_or_imm
      Load   : $ld ($iN) $rd [$rb + off_or_reg]
      Store  : $st ($iN) [$rb + off_or_reg] $rs
      Set    : $set $rd N val
      Branch : ? ($iN) $r op $goto label
      Call   : $call label
      Return : $return
      Halt   : $halt
      Null   : $null
    """
    t = text.strip()
    NONE3 = (frozenset(), frozenset(), False, None, None)

    if not t or t == '$null':
        return NONE3

    if t in ('$halt', '$return'):
        return frozenset(), frozenset(), True, None, None

    if t.startswith('$call'):
        # $call clobbers r1 (return value written on return)
        return frozenset({'$r1'}), frozenset(), True, None, None

    if t.startswith('$set'):
        # $set $rd N val  →  writes rd
        m = re.match(r'\$set\s+(\$r\d+)', t)
        return (frozenset({m.group(1)}) if m else frozenset()), frozenset(), False, None, None

    if t.startswith('$ld'):
        # $ld ($iN) $rd [$rb + off]   off = integer or $reg
        m = re.match(r'\$ld\s+\(\$i\d+\)\s+(\$r\d+)\s+\[(\$r\d+)\s*\+\s*(-?\d+|\$r\d+)\]', t)
        if m:
            rd, rb, off = m.group(1), m.group(2), m.group(3)
            reads = {rb}
            if off.startswith('$r'):
                reads.add(off)
            return frozenset({rd}), frozenset(reads), False, (rb, off), None
        return frozenset(), frozenset(), False, None, None

    if t.startswith('$st'):
        # $st ($iN) [$rb + off] $rs   off = integer or $reg
        m = re.match(r'\$st\s+\(\$i\d+\)\s+\[(\$r\d+)\s*\+\s*(-?\d+|\$r\d+)\]\s+(\$r\d+)', t)
        if m:
            rb, off, rs = m.group(1), m.group(2), m.group(3)
            reads = {rb, rs}
            if off.startswith('$r'):
                reads.add(off)
            return frozenset(), frozenset(reads), False, (rb, off), (rb, off)
        return frozenset(), frozenset(), False, None, None

    if t.startswith('$pack'):
        # $pack packed_nbits rd word_nbits rs2
        # rs2 and rs2+1 form a consecutive register pair — BOTH are read, even though
        # only rs2 appears in the text. Missing this caused a RAW hazard to go undetected
        # when an adjacent instruction wrote rs2+1 in the same bundle (found 2026-06-17).
        m = re.match(r'\$pack\s+\d+\s+(\$r\d+)\s+\d+\s+(\$r\d+)', t)
        if m:
            rd, rs2 = m.group(1), m.group(2)
            partner = f'$r{int(rs2[2:]) + 1}'
            return frozenset({rd}), frozenset({rs2, partner}), False, None, None
        return NONE3

    if t.startswith('$cast'):
        # $cast (dest_type) rd (src_type) rs
        m = re.match(r'\$cast\s+\(\$\w+\)\s+(\$r\d+)\s+\(\$\w+\)\s+(\$r\d+)', t)
        if m:
            rd, rs = m.group(1), m.group(2)
            return frozenset({rd}), frozenset({rs}), False, None, None
        return NONE3

    if t.startswith('$fsqrt'):
        # $fsqrt rd (type) rs
        m = re.match(r'\$fsqrt\s+(\$r\d+)\s+\(\$\w+\)\s+(\$r\d+)', t)
        if m:
            rd, rs = m.group(1), m.group(2)
            return frozenset({rd}), frozenset({rs}), False, None, None
        return NONE3

    if t.startswith('$cmov'):
        # $cmov ? (type) check cond rd src_true
        # rd is BOTH read (kept unchanged if the condition is false) and written.
        m = re.match(r'\$cmov\s+\?\s+\(\$\w+\)\s+(\$r\d+)\s+\S+\s+(\$r\d+)\s+(\$r\d+)', t)
        if m:
            check, rd, src_true = m.group(1), m.group(2), m.group(3)
            return frozenset({rd}), frozenset({check, rd, src_true}), False, None, None
        return NONE3

    if t.startswith('$slice'):
        # $slice rd hindex lindex rs
        m = re.match(r'\$slice\s+(\$r\d+)\s+\d+\s+\d+\s+(\$r\d+)', t)
        if m:
            rd, rs = m.group(1), m.group(2)
            return frozenset({rd}), frozenset({rs}), False, None, None
        return NONE3

    if t.startswith('$v ') or t.startswith('$v\t'):
        # $v op rd (type) rs1 rs2 [$replicate]
        m = re.match(r'\$v\s+\S+\s+(\$r\d+)\s+\(\$\w+\)\s+(\$r\d+)\s+(\$r\d+)', t)
        if m:
            rd, rs1, rs2 = m.group(1), m.group(2), m.group(3)
            return frozenset({rd}), frozenset({rs1, rs2}), False, None, None
        return NONE3

    if t.startswith('$dot'):
        # $dot [$accumulate] rd (type) rs1 rs2
        # accumulate form also READS rd (rd := (rs1 dot rs2) + rd).
        m = re.match(r'\$dot\s+(\$accumulate\s+)?(\$r\d+)\s+\(\$\w+\)\s+(\$r\d+)\s+(\$r\d+)', t)
        if m:
            accumulate, rd, rs1, rs2 = m.group(1), m.group(2), m.group(3), m.group(4)
            reads = {rs1, rs2}
            if accumulate:
                reads.add(rd)
            return frozenset({rd}), frozenset(reads), False, None, None
        return NONE3

    if t.startswith('$vreduce'):
        # $vreduce + rd (type) rs  (sub-opcode '+' required by the grammar)
        m = re.match(r'\$vreduce\s+\S+\s+(\$r\d+)\s+\(\$\w+\)\s+(\$r\d+)', t)
        if m:
            rd, rs = m.group(1), m.group(2)
            return frozenset({rd}), frozenset({rs}), False, None, None
        return NONE3

    if t.startswith('?'):
        # ? ($iN) $r op $goto label  →  reads r; ends bundle
        m = re.match(r'\?\s+\(\$i\d+\)\s+(\$r\d+)', t)
        reads = frozenset({m.group(1)}) if m else frozenset()
        return frozenset(), reads, True, None, None

    # ALU: op $rd ($iN) $rs1 rs2_or_imm
    # op may be: + - * / << >> | & ^ ~| ~& ~^
    m = re.match(r'([+\-*/<>&|^~]{1,3})\s+(\$r\d+)\s+\(\$i\d+\)\s+(\$r\d+)\s+(-?\d+|\$r\d+)', t)
    if m:
        rd, rs1, rs2 = m.group(2), m.group(3), m.group(4)
        reads = {rs1}
        if rs2.startswith('$r'):
            reads.add(rs2)
        reads.discard('$r0')   # $r0 is always-zero hardware constant — never a real dep
        return frozenset({rd}), frozenset(reads), False, None, None

    return NONE3


# ── Mcode text parser ──────────────────────────────────────────────────────────

def _parse_flat(mcode_text):
    """
    Parse mcode text into a flat list of instruction dicts:
      { 'text': str, 'labels': [str], 'writes': frozenset,
        'reads': frozenset, 'is_ctrl': bool }

    Also returns the header lines (comments/blanks before first bundle).
    """
    lines = mcode_text.split('\n')
    flat          = []
    pending_lbl   = []
    header        = []
    seen_content  = False
    i = 0

    while i < len(lines):
        line = lines[i]
        s    = line.strip()
        i   += 1

        # Collect header (comments / blanks before first label or bundle)
        if not seen_content:
            if not s or s.startswith('//'):
                header.append(line)
                continue

        if not s or s.startswith('//'):
            continue

        # Label line
        if s.endswith(':') and s != '||':
            seen_content = True
            pending_lbl.append(s[:-1])
            continue

        # Bundle open
        if s == '||':
            seen_content = True
            bundle_texts = []
            while i < len(lines) and lines[i].strip() != ';':
                t = lines[i].strip()
                if t and t != '$null':
                    bundle_texts.append(t)
                i += 1
            i += 1  # skip ';'

            if bundle_texts:
                for j, itext in enumerate(bundle_texts):
                    w, r, ctrl, mem_access, mem_write = _parse_deps(itext)
                    flat.append({
                        'text':       itext,
                        'labels':     pending_lbl if j == 0 else [],
                        'writes':     w,
                        'reads':      r,
                        'is_ctrl':    ctrl,
                        'mem_access': mem_access,
                        'mem_write':  mem_write,
                    })
                    pending_lbl = []
            else:
                # Empty bundle carrying only labels (e.g. trailing label)
                if pending_lbl:
                    flat.append({
                        'text': '$null', 'labels': pending_lbl,
                        'writes': frozenset(), 'reads': frozenset(), 'is_ctrl': False,
                        'mem_access': None, 'mem_write': None,
                    })
                    pending_lbl = []

    return header, flat


# ── Greedy bundle packer ───────────────────────────────────────────────────────

def _pack_bundles(flat):
    """
    Greedy forward pass: pack instructions into bundles of up to 8.
    Returns list of {'labels': [...], 'instrs': [str]}.
    """
    bundles    = []
    c_labels   = []
    c_instrs   = []
    c_writes   = set()
    c_mem_writes = set()   # (base, offset) addresses stored-to in this bundle
    c_mem_reads  = set()   # registers read by $ld/$st instructions in this bundle
    c_ctrl     = False

    def flush():
        if c_instrs or c_labels:
            bundles.append({'labels': list(c_labels), 'instrs': list(c_instrs)})

    def reset():
        c_labels.clear(); c_instrs.clear(); c_writes.clear(); c_mem_writes.clear()
        c_mem_reads.clear()
        nonlocal c_ctrl; c_ctrl = False

    # ABI-fixed stack-pointer register (matches codegen.py's SP = '$r27'). bundler.py
    # works purely on parsed text and doesn't otherwise know ABI register roles, so
    # this is hardcoded rather than imported.
    SP_REG = '$r27'

    for instr in flat:
        is_mem  = instr['mem_access'] is not None
        is_call = instr['text'].startswith('$call')
        split = False
        if c_instrs:
            if instr['labels']:                         split = True  # label → new bundle
            elif c_ctrl:                                split = True  # ctrl ends bundle
            elif instr['reads']  & c_writes:           split = True  # RAW hazard
            elif instr['writes'] & c_writes:           split = True  # WAW hazard
            elif instr['mem_access'] in c_mem_writes:   split = True  # memory RAW/WAW hazard
            # Phase hazard: the aligner places $ld/$st in LATER slots than ALU/$set
            # instructions within a bundle, regardless of textual order — confirmed
            # 2026-06-17 by comparing unaligned vs aligned mcode (e.g. every function
            # prologue's "$st [SP+0] OLD_FP" + "+FP=SP" bundle: the store textually
            # comes first to capture the OLD FP, but the aligner moves it to a later
            # slot than the FP update, so it ends up storing the NEW FP instead).
            # So a non-memory instruction writing a register that an already-bundled
            # memory instruction reads is unsafe — the memory read will see the new
            # (post-ALU) value, not the pre-bundle one the compiler intended.
            elif not is_mem and (instr['writes'] & c_mem_reads): split = True
            # Conservative fix (2026-06-17): never bundle $call with an instruction
            # that modifies SP. The exact phase interaction between an SP-modifying
            # ALU instruction and a co-bundled $call is unconfirmed (breaks even the
            # simplest possible function call — see memory/project_call_phase_hazard.md)
            # — rather than guess at the precise mechanism, force them into separate
            # bundles. This pattern only occurs near call sites, so the cost is a few
            # extra instruction slots, not a systemic bundling regression.
            elif is_call and SP_REG in c_writes:        split = True
            elif len(c_instrs) >= 8:                   split = True  # bundle full

        if split:
            flush(); reset()

        c_labels.extend(instr['labels'])
        c_instrs.append(instr['text'])
        c_writes |= instr['writes']
        if instr['mem_write'] is not None:
            c_mem_writes.add(instr['mem_write'])
        if is_mem:
            c_mem_reads |= instr['reads']
        c_ctrl    = c_ctrl or instr['is_ctrl']

    flush()
    return bundles


def _merge_duplicate_labels(bundles):
    """
    The assembler grammar only allows one label directly before a bundle's '||'
    (confirmed: "expecting PARALLEL, found <label>" if a second one follows).
    When a bundle ends up with multiple labels — e.g. an inner for-loop's exit
    label lands on the exact same bundle as an outer loop's increment label,
    with no real instruction between them — collapse them to one canonical
    label and rewrite every $goto/$call reference to the dropped labels so
    they point at the canonical one instead. ($call $rN, register-indirect,
    is never matched here since the regex requires a bare identifier with no
    leading $.)
    """
    rename = {}
    for b in bundles:
        if len(b['labels']) > 1:
            canonical = b['labels'][0]
            for extra in b['labels'][1:]:
                rename[extra] = canonical
            b['labels'] = [canonical]
    if not rename:
        return bundles
    pattern = re.compile(r'(\$goto|\$call)(\s+)(\w+)')
    def _sub(m):
        kw, sp, lbl = m.group(1), m.group(2), m.group(3)
        return f"{kw}{sp}{rename.get(lbl, lbl)}"
    for b in bundles:
        b['instrs'] = [pattern.sub(_sub, itext) for itext in b['instrs']]
    return bundles


# ── Emitter ───────────────────────────────────────────────────────────────────

def _emit_bundles(header, bundles):
    out = list(header)
    for b in bundles:
        for lbl in b['labels']:
            out.append(f"{lbl}:")
        out.append("||")
        for itext in b['instrs']:
            out.append(f"    {itext}")
        out.append(";")
    return '\n'.join(out) + '\n'


# ── Public API ────────────────────────────────────────────────────────────────

def bundle_mcode(mcode_text):
    """
    Repack mcode from 1-instruction bundles into VLIW bundles (max 8).

    Returns:
        (new_mcode_text: str, n_before: int, n_after: int)
    """
    header, flat  = _parse_flat(mcode_text)
    n_before      = sum(1 for x in flat if x['text'] != '$null')
    bundles       = _pack_bundles(flat)
    bundles       = _merge_duplicate_labels(bundles)
    n_after       = len(bundles)
    new_mcode     = _emit_bundles(header, bundles)
    return new_mcode, n_before, n_after
