"""
APARA Compiler — IR → APARA mcode  (v4: Pending Labels & Shared Epilogue)

Register conventions:
  $r0  = always zero (hardware read-only)
  $r1  = return value
  $r2-$r5  = function arguments (up to 4)
  $r6-$r22 = general temporaries (17 regs)
  $r23 = caller-save-index scratch
  $r24 = always-1  (set in every prologue — used for unconditional jumps)
  $r25 = scratch (address computation, temp spills)
  $r26 = frame pointer (FP)
  $r27 = stack pointer (SP)
  $r28 = global-base register (GBASE) — set once in _start, never modified
  $r29-$r31 = reserved
"""

from ir import *

ZERO  = '$r0'
RET   = '$r1'
ARG   = ['$r2', '$r3', '$r4', '$r5']
GEN   = [f'$r{i}' for i in range(6, 23)]   # 17 general regs ($r6..$r22)
SCIDX = '$r23'   # spare scratch (caller-save index / overflow temp)
ONE   = '$r24'   # always 1
SCR   = '$r25'   # primary scratch / address scratch
FP    = '$r26'
SP    = '$r27'
GBASE = '$r28'   # global base address register

CALLER_SAVE_BYTES = len(GEN) * 4   # 68 bytes reserved below locals for reg spill


# ── Register allocator ────────────────────────────────────────────────────────

class RegAlloc:
    def __init__(self):
        self._map  = {}
        self._pool = list(GEN)

    def reg(self, temp):
        name = temp.name if isinstance(temp, Temp) else str(temp)
        if name not in self._map:
            self._map[name] = self._pool.pop(0) if self._pool else SCR
        return self._map[name]

    def items(self):
        return list(self._map.items())


# ── Code generator ────────────────────────────────────────────────────────────

class CodeGen:

    def __init__(self, global_base=0x400):
        self._lines       = []
        self._ra          = RegAlloc()
        self._global_base = global_base
        self._decl_frame  = 0
        self._init_code   = []
        self._pending_labels = []  # Holds labels until the next instruction bundle

    # ── public interface ──────────────────────────────────────────────────────

    def generate(self, ir_instructions, global_base=None):
        if global_base is not None:
            self._global_base = global_base
        self._lines = []
        self._init_code = []
        self._ra = RegAlloc()
        self._pending_labels = []

        for ir in ir_instructions:
            self._gen(ir)

        # Ensure trailing labels at EOF are not lost
        if self._pending_labels:
            for lbl in self._pending_labels:
                self._lines.append(f"{lbl}:")
            self._lines.extend(["||", "    $null", ";"])

        return '\n'.join(self._lines) + '\n'

    def startup_code(self, global_base=None, stack_top=0x7FF8):
        gb = global_base if global_base is not None else self._global_base
        out = [
            "// ── APARA startup (generated by APARA C Compiler v4) ─────────────────────────",
            f"// GBASE = 0x{gb:x}   stack_top = 0x{stack_top:x}",
            "apara_start:",
        ]

        def b(instr):
            out.extend(["||", f"    {instr}", ";"])

        # Load GBASE = gb
        self._emit_set_const_into(gb, GBASE, b)
        # Load SP = stack_top
        self._emit_set_const_into(stack_top, SP, b)

        # FP = SP
        b(f"+ {FP} ($i32) {ZERO} {SP}")
        # ONE = 1
        b(f"+ {ONE} ($i32) {ZERO} 1")

        for line in self._init_code:
            out.append(line)

        b(f"$call main")
        b(f"$halt")
        out.append("")
        return '\n'.join(out)

    # ── emit helpers ──────────────────────────────────────────────────────────

    def _emit(self, instr, label=None):
        """Emit a single-instruction bundle, attaching any pending labels."""
        if label:
            self._pending_labels.append(label)

        # Flush the label queue right before opening the bundle
        for lbl in self._pending_labels:
            self._lines.append(f"{lbl}:")
        self._pending_labels = []

        self._lines.append("||")
        self._lines.append(f"    {instr}")
        self._lines.append(";")

    # ── constant loading ──────────────────────────────────────────────────────

    def _load_const(self, reg, value):
        value = int(value)
        if -512 <= value <= 511:
            self._emit(f"+ {reg} ($i32) {ZERO} {value}")
        elif 0 <= value <= 65535:
            self._emit(f"$set {reg} 0 {value}")
        else:
            lo = value & 0xFFFF
            hi = (value >> 16) & 0xFFFF
            self._emit(f"$set {reg} 0 {lo}")
            if hi:
                self._emit(f"$set {reg} 2 {hi}")

    def _emit_set_const_into(self, value, reg, emit_fn):
        value = int(value)
        if -512 <= value <= 511:
            emit_fn(f"+ {reg} ($i32) {ZERO} {value}")
        elif 0 <= value <= 65535:
            emit_fn(f"$set {reg} 0 {value}")
        else:
            lo = value & 0xFFFF
            hi = (value >> 16) & 0xFFFF
            emit_fn(f"$set {reg} 0 {lo}")
            if hi:
                emit_fn(f"$set {reg} 2 {hi}")

    def _op2reg(self, op):
        if isinstance(op, Const):
            self._load_const(SCR, op.value)
            return SCR
        return self._ra.reg(op)

    def _atype(self, elem_bytes):
        return {1: '($i8)', 2: '($i16)', 4: '($i32)', 8: '($i64)'}.get(elem_bytes, '($i32)')

    # ── comparison / branch ───────────────────────────────────────────────────

    def _emit_cond_branch(self, left, op, right, true_lbl, false_lbl):
        l_reg = self._op2reg(left)
        if l_reg == SCR and not isinstance(right, Const):
            self._emit(f"+ {SCIDX} ($i32) {ZERO} {SCR}")
            l_reg = SCIDX

        r_is_zero = isinstance(right, Const) and right.value == 0

        if r_is_zero:
            if op in ('<', '<='):
                self._emit(f"- {SCR} ($i32) {ZERO} {l_reg}")
                apara_op = '>' if op == '<' else '>='
                self._emit(f"? ($i32) {SCR} {apara_op} $goto {true_lbl}")
            else:
                apara_op = op
                self._emit(f"? ($i32) {l_reg} {apara_op} $goto {true_lbl}")
        else:
            r_reg = self._op2reg(right)
            if op in ('>', '>=', '==', '!='):
                self._emit(f"- {SCR} ($i32) {l_reg} {r_reg}")
                self._emit(f"? ($i32) {SCR} {op} $goto {true_lbl}")
            elif op in ('<', '<='):
                self._emit(f"- {SCR} ($i32) {r_reg} {l_reg}")
                apara_op = '>' if op == '<' else '>='
                self._emit(f"? ($i32) {SCR} {apara_op} $goto {true_lbl}")

        if false_lbl:
            self._emit_jump(false_lbl)

    def _emit_jump(self, label):
        self._emit(f"? ($i32) {ONE} > $goto {label}")

    # ── dispatch ──────────────────────────────────────────────────────────────

    def _gen(self, ir):
        method = getattr(self, f'_gen_{type(ir).__name__}', None)
        if method:
            method(ir)

    # ── global variable initializer ───────────────────────────────────────────

    def _gen_IRGlobalDecl(self, ir):
        if not ir.init:
            return
        at     = self._atype(ir.elem_bytes)
        offset = ir.dmem_addr - self._global_base

        for i, val in enumerate(ir.init):
            byte_off = offset + i * ir.elem_bytes
            lines = []

            val = int(val)
            if -512 <= val <= 511:
                lines += ["||", f"    + {SCR} ($i32) {ZERO} {val}", ";"]
            elif 0 <= val <= 65535:
                lines += ["||", f"    $set {SCR} 0 {val}", ";"]
            else:
                lo = val & 0xFFFF; hi = (val >> 16) & 0xFFFF
                lines += ["||", f"    $set {SCR} 0 {lo}", ";"]
                if hi:
                    lines += ["||", f"    $set {SCR} 2 {hi}", ";"]

            if 0 <= byte_off <= 511:
                lines += ["||", f"    $st {at} [{GBASE} + {byte_off}] {SCR}", ";"]
            else:
                lo2 = byte_off & 0xFFFF; hi2 = (byte_off >> 16) & 0xFFFF
                lines += ["||", f"    $set {SCIDX} 0 {lo2}", ";"]
                if hi2:
                    lines += ["||", f"    $set {SCIDX} 2 {hi2}", ";"]
                lines += ["||", f"    $st {at} [{GBASE} + {SCIDX}] {SCR}", ";"]

            self._init_code.extend(lines)

    # ── function prologue / epilogue ──────────────────────────────────────────

    def _gen_IRFuncBegin(self, ir):
        self._ra = RegAlloc()
        self._decl_frame = ir.frame_size
        self._current_epilogue = f"{ir.name}_epilogue"

        # Queue the function name label to be placed on the first instruction
        self._pending_labels.append(ir.name)

        self._emit(f"$st ($i32) [{SP} + 0] {FP}")
        self._emit(f"+ {FP} ($i32) {ZERO} {SP}")
        fs = ir.frame_size + CALLER_SAVE_BYTES
        if fs <= 511:
            self._emit(f"- {SP} ($i32) {SP} {fs}")
        else:
            self._load_const(SCR, fs)
            self._emit(f"- {SP} ($i32) {SP} {SCR}")
        self._emit(f"+ {ONE} ($i32) {ZERO} 1")

        for i, (pname, fp_off) in enumerate(ir.params):
            if i >= len(ARG):
                break
            self._emit(f"$st ($i32) [{FP} + {fp_off}] {ARG[i]}")

    def _gen_IRFuncEnd(self, ir):
        # Attach the shared epilogue label
        self._pending_labels.append(self._current_epilogue)
        self._emit_epilogue()

    def _emit_epilogue(self):
        self._emit(f"+ {SP} ($i32) {ZERO} {FP}")
        self._emit(f"$ld ($i32) {FP} [{SP} + 0]")
        self._emit("$return")

    # ── labels / jumps ────────────────────────────────────────────────────────

    def _gen_IRLabel(self, ir):
        # Queue the label so it attaches to the next emitted bundle
        self._pending_labels.append(ir.name)

    def _gen_IRJump(self, ir):
        self._emit_jump(ir.label)

    def _gen_IRCondJump(self, ir):
        self._emit_cond_branch(ir.left, ir.op, ir.right, ir.true_label, ir.false_label)

    # ── data movement ─────────────────────────────────────────────────────────

    def _gen_IRAssign(self, ir):
        dest = self._ra.reg(ir.dest)
        if isinstance(ir.src, Const):
            self._load_const(dest, ir.src.value)
        else:
            src = self._ra.reg(ir.src)
            self._emit(f"+ {dest} ($i32) {ZERO} {src}")

    def _gen_IRLoadAddr(self, ir):
        dest   = self._ra.reg(ir.dest)
        fp_off = ir.fp_offset
        if -512 <= fp_off <= 511:
            self._emit(f"+ {dest} ($i32) {FP} {fp_off}")
        else:
            self._load_const(SCR, fp_off)
            self._emit(f"+ {dest} ($i32) {FP} {SCR}")

    def _gen_IRLoad(self, ir):
        dest = self._ra.reg(ir.dest)
        at   = self._atype(ir.elem_bytes)
        base = self._op2reg(ir.base)
        if base == SCR:
            self._emit(f"+ {SCIDX} ($i32) {ZERO} {SCR}")
            base = SCIDX

        if isinstance(ir.offset, Const):
            off = ir.offset.value
            if -512 <= off <= 511:
                self._emit(f"$ld {at} {dest} [{base} + {off}]")
            else:
                self._load_const(SCR, off)
                self._emit(f"$ld {at} {dest} [{base} + {SCR}]")
        else:
            off_reg = self._ra.reg(ir.offset)
            self._emit(f"$ld {at} {dest} [{base} + {off_reg}]")

    def _gen_IRStore(self, ir):
        at  = self._atype(ir.elem_bytes)
        src = self._op2reg(ir.src)
        if src == SCR:
            self._emit(f"+ {SCIDX} ($i32) {ZERO} {SCR}")
            src = SCIDX

        base = self._op2reg(ir.base)

        if isinstance(ir.offset, Const):
            off = ir.offset.value
            if -512 <= off <= 511:
                self._emit(f"$st {at} [{base} + {off}] {src}")
            else:
                self._load_const(SCR, off)
                self._emit(f"$st {at} [{base} + {SCR}] {src}")
        else:
            off_reg = self._ra.reg(ir.offset)
            self._emit(f"$st {at} [{base} + {off_reg}] {src}")

    # ── global variable access ─────────────────────────────────────────────────

    def _gen_IRGlobalLoad(self, ir):
        dest   = self._ra.reg(ir.dest)
        at     = self._atype(ir.elem_bytes)
        goff   = ir.dmem_addr - self._global_base

        if isinstance(ir.offset, Const) and ir.offset.value == 0:
            if 0 <= goff <= 511:
                self._emit(f"$ld {at} {dest} [{GBASE} + {goff}]")
            else:
                self._load_const(SCR, goff)
                self._emit(f"$ld {at} {dest} [{GBASE} + {SCR}]")
        else:
            off_reg = self._op2reg(ir.offset)
            if off_reg == SCR:
                self._emit(f"+ {SCIDX} ($i32) {ZERO} {SCR}")
                off_reg = SCIDX
            if 0 <= goff <= 511:
                self._emit(f"+ {SCR} ($i32) {off_reg} {goff}")
            else:
                self._load_const(dest, goff)
                self._emit(f"+ {SCR} ($i32) {dest} {off_reg}")
            self._emit(f"$ld {at} {dest} [{GBASE} + {SCR}]")

    def _gen_IRGlobalStore(self, ir):
        at   = self._atype(ir.elem_bytes)
        goff = ir.dmem_addr - self._global_base

        src = self._op2reg(ir.src)
        if src == SCR:
            self._emit(f"+ {SCIDX} ($i32) {ZERO} {SCR}")
            src = SCIDX

        if isinstance(ir.offset, Const) and ir.offset.value == 0:
            if 0 <= goff <= 511:
                self._emit(f"$st {at} [{GBASE} + {goff}] {src}")
            else:
                self._load_const(SCR, goff)
                self._emit(f"$st {at} [{GBASE} + {SCR}] {src}")
        else:
            off_reg = self._op2reg(ir.offset)
            if off_reg == SCR:
                self._emit(f"+ {SCIDX} ($i32) {ZERO} {SCR}")
                off_reg = SCIDX
            if 0 <= goff <= 511:
                self._emit(f"+ {SCR} ($i32) {off_reg} {goff}")
            else:
                self._load_const(SCIDX, goff)
                self._emit(f"+ {SCR} ($i32) {SCIDX} {off_reg}")
            self._emit(f"$st {at} [{GBASE} + {SCR}] {src}")

    def _gen_IRGlobalAddrOf(self, ir):
        dest = self._ra.reg(ir.dest)
        goff = ir.dmem_addr - self._global_base
        if isinstance(ir.offset, Const) and ir.offset.value == 0:
            if 0 <= goff <= 511:
                self._emit(f"+ {dest} ($i32) {GBASE} {goff}")
            else:
                self._load_const(SCR, goff)
                self._emit(f"+ {dest} ($i32) {GBASE} {SCR}")
        else:
            off_reg = self._op2reg(ir.offset)
            self._load_const(SCR, goff)
            self._emit(f"+ {SCR} ($i32) {SCR} {off_reg}")
            self._emit(f"+ {dest} ($i32) {GBASE} {SCR}")

    # ── arithmetic ────────────────────────────────────────────────────────────

    _APARA_OP = {
        '+':  '+',
        '-':  '-',
        '*':  '*',
        '/':  '/',
        '<<': '<<',
        '>>': '>>',
        '|':  '|',
        '&':  '&',
        '^':  '^',
        '~|': '~|',
        '~&': '~&',
        '~^': '~^',
    }

    def _gen_IRBinOp(self, ir):
        dest = self._ra.reg(ir.dest)
        op   = ir.op

        if isinstance(ir.left, Const) and isinstance(ir.right, Const):
            lv, rv = ir.left.value, ir.right.value
            try:
                result = {
                    '+': lv + rv, '-': lv - rv, '*': lv * rv,
                    '/': int(lv / rv) if rv != 0 else 0,
                    '%': lv % rv if rv != 0 else 0,
                    '&': lv & rv, '|': lv | rv, '^': lv ^ rv,
                    '<<': lv << rv, '>>': lv >> rv,
                }.get(op)
                if result is not None:
                    self._load_const(dest, result)
                    return
            except Exception:
                pass

        if op == '%':
            l_reg = self._op2reg(ir.left)
            if l_reg == SCR:
                self._emit(f"+ {SCIDX} ($i32) {ZERO} {SCR}")
                l_reg = SCIDX
            r_reg = self._op2reg(ir.right)
            self._emit(f"/ {SCIDX} ($i32) {l_reg} {r_reg}")
            self._emit(f"* {SCIDX} ($i32) {SCIDX} {r_reg}")
            self._emit(f"- {dest} ($i32) {l_reg} {SCIDX}")
            return

        apara = self._APARA_OP.get(op, op)

        l_reg = self._op2reg(ir.left)
        if l_reg == SCR:
            self._emit(f"+ {SCIDX} ($i32) {ZERO} {SCR}")
            l_reg = SCIDX

        if isinstance(ir.right, Const):
            rv = ir.right.value
            if -512 <= rv <= 511:
                self._emit(f"{apara} {dest} ($i32) {l_reg} {rv}")
            else:
                self._load_const(SCR, rv)
                self._emit(f"{apara} {dest} ($i32) {l_reg} {SCR}")
        else:
            r_reg = self._ra.reg(ir.right)
            self._emit(f"{apara} {dest} ($i32) {l_reg} {r_reg}")

    def _gen_IRUnaryOp(self, ir):
        dest = self._ra.reg(ir.dest)
        op   = ir.op
        src  = self._op2reg(ir.operand)
        if op == '-':
            self._emit(f"- {dest} ($i32) {ZERO} {src}")
        elif op == '~':
            self._emit(f"^ {dest} ($i32) {src} -1")
        else:
            self._emit(f"+ {dest} ($i32) {ZERO} {src}")

    # ── function calls ─────────────────────────────────────────────────────────

    def _gen_IRCall(self, ir):
        fname = ir.func_name

        if fname == 'halt':
            self._emit("$halt")
            return

        saved = self._ra.items()
        for idx, (_, reg) in enumerate(saved):
            slot = -(self._decl_frame + 4 + idx * 4)
            self._emit(f"$st ($i32) [{FP} + {slot}] {reg}")

        for i, arg in enumerate(ir.args[:4]):
            if isinstance(arg, Const):
                self._load_const(ARG[i], arg.value)
            else:
                arg_reg = self._ra.reg(arg)
                self._emit(f"+ {ARG[i]} ($i32) {ZERO} {arg_reg}")

        self._emit(f"$call {fname}")

        for idx, (_, reg) in enumerate(saved):
            slot = -(self._decl_frame + 4 + idx * 4)
            self._emit(f"$ld ($i32) {reg} [{FP} + {slot}]")

        self._emit(f"+ {ONE} ($i32) {ZERO} 1")

        if ir.dest is not None:
            dest = self._ra.reg(ir.dest)
            self._emit(f"+ {dest} ($i32) {ZERO} {RET}")

    # ── return ────────────────────────────────────────────────────────────────

    def _gen_IRReturn(self, ir):
        if ir.value is not None:
            if isinstance(ir.value, Const):
                self._load_const(RET, ir.value.value)
            else:
                src = self._ra.reg(ir.value)
                self._emit(f"+ {RET} ($i32) {ZERO} {src}")

        # Jump to the single shared epilogue block
        self._emit_jump(self._current_epilogue)

    def _gen_IRHalt(self, ir):
        self._emit("$halt")
