#!/bin/bash
# Auto-generated by APARA C Compiler — edit BIN_DIR to match your installation
BIN_DIR=../../../assembler/bin
ALIGN=$BIN_DIR/mcode_align
AS=$BIN_DIR/mcode_assemble
DISAS=$BIN_DIR/mcode_disassemble
RUN=$BIN_DIR/mcode_run

NAME=test

$ALIGN  $NAME.mcode           > $NAME.aligned.mcode
$AS     $NAME.aligned.mcode   > $NAME.obj
$DISAS  $NAME.obj             > $NAME.disass.mcode
$RUN -p 0x0 -i $NAME.obj -d data.map -r $NAME.result -v 2>&1 | tee $NAME.log
